### ISSUE TITLE
The inference results is different after converting to onnx model

### ISSUE THREAD

**Issue by KevinHexin** [vita-epfl/openpifpaf#102]
Hi, thanks for your great job.
while i'm trying to convert the pytorch model to onnx format model in order to use onnxruntime with c++ api, i used the python module "export_onnx.py". After export the onnx format model and follow this https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html example to checkout the results, i got 99.8% mismatch.
I also wrote a c++ code to load onnx model through onnxruntime API, and the inference results is different with pytorch too. So i think the exported onnx model is not correct, what should i do? is this a bug or something? Look forward to your reply。

Pytorch version V1.1.0

**Comment by svenkreiss** [comment]
Thanks for reporting this. So far I had only tested with onnx.js and it wasn't working there either but at least the exporter ran.

Here is a list of ONNX limitations in PyTorch: https://github.com/pytorch/pytorch/blob/master/docs/source/onnx.rst#limitations

Here is an open PyTorch issue that does seem to have pinpointed the problem to the ONNX export of PixelShuffle: https://github.com/pytorch/pytorch/issues/18429
This issue even suggests an alternative PixelShuffle implementation that works with ONNX:
https://gist.github.com/geoffsmith/0b69070e96262dffe4ae1c22e9126bf3

**Comment by svenkreiss** [comment]
The master branch in combination with the new PyTorch 1.2 can export a ResNet50 model that works very well for me. Does that fix it for you, too?

**Comment by KevinHexin** [comment]
> The master branch in combination with the new PyTorch 1.2 can export a ResNet50 model that works very well for me. Does that fix it for you, too? @KevinHexin

yes, Pytorch 1.2 is working well, LOL.
Actually after I failed convert ONNX with PyTorch1.1,  I re-implemented your OpenPifPaf-ResNet50 use TensorRT netowork API and C++.
And With in-depth experiments, i mainly compared openpose. I found OpenPifPaf-ResNet50 is not working much better than openpose.
I run OpenPifPaf-ResNet50 with 501x501 resolution and openpose with 656x368 resolution and use GitHub newest version.
1. in higher resolution, OpenPIfPaf got more false detection than in lower resolution(seems like work better with small human).
2. some complex human pose, like people lying on the ground, OpenPIfPaf dose not work well.
3. pose jitter, the results are more unstable than openpose.
And OpenPifPaf use about 125 ms and openpose use about 160 ms per image with GTX-1050TI.
Maybe i use resnet101 an backbone could work better but time consuming may not acceptable.

**Comment by svenkreiss** [comment]
Thanks for confirming it works with PyTorch 1.2.

To your observations:
1. Indeed. This is still experimental, but try `--two-scale` to improve large person instances.
2. Yes. I am seeing that, too. Working on an augmentation for that.
3. I am surprised by that. Is that for difficult poses?

A few weeks ago I added some timing numbers to the README. My numbers are quite a bit better than yours. I use a 1080Ti which is a bit bigger but I didn't expect such a difference. But I also expected OpenPose to be faster. Interesting.
