### ISSUE TITLE
Why didn't I generate any information?

### ISSUE THREAD

**Issue by Mindisblown** [vita-epfl/openpifpaf#103]
Hi,thanks for you great job! 
I changed the number of joint points and trained the network. However, there is no information when using a trained model to predict. I want to know the reason for this situation.

**Comment by svenkreiss** [comment]
Hi @Mindisblown , you will have to go into the code to adjust number of keypoints in quite a few places. It's not easily supported from us at the moment but we might put something in in the future. Did you come across a specific issue I can help with?
