### ISSUE TITLE
Why comes out ERROR when I try to eval the Networks using Multi-Scale

### ISSUE THREAD

**Issue by mengfanShi** [vita-epfl/openpifpaf#108]
When I eval with a single scale, all right. 
But when I add --multi-scale or --three-scale, There comes an error:
**File "/pifpaf/openpifpaf/openpifpaf/transforms.py", line 372, in __call__
    ann['keypoints'][:, 0] = -ann['keypoints'][:, 0] - 1.0 + w
TypeError: list indices must be integers or slices, not tuple**

**Comment by svenkreiss** [comment]
Multi-scale and three-scale were experimental features that did not show
performance improvements. The latest version contains a new form of
`--two-scale` that actually improves results, but also this is still
experimental.

**Comment by tfzhou** [comment]
The `--two-scale` option works well in my cases (not on coco dataset). It improve the mAP by about 2 points.
