### ISSUE TITLE
output shape problem

### ISSUE THREAD

**Issue by qiuzhongwei-USTB** [vita-epfl/openpifpaf#109]
when i evaluate with batch size >=2, the output size is 81*81.
But when i change batch size as 1, the output size is 53*81.
Is there something wrong?

**Comment by qiuzhongwei-USTB** [comment]
[17,81,81] and [19,53,81]

**Comment by svenkreiss** [comment]
No.

When batch size is >=2, black bars are added to the sides of the image to
create uniform image sizes for batching. That step is not necessary when
batch size is 1.
