### ISSUE TITLE
Will python programs in the project call C++programs? Why are there C++programs here.

### ISSUE THREAD

**Issue by liudadan** [vita-epfl/openpifpaf#11]
Will python programs in the project call C++programs? Why are there C++programs here.

**Comment by taylormordan** [comment]
Decoders have been implemented in C++ for faster inference than in Python.
They are defined ([here](https://github.com/vita-epfl/openpifpaf/blob/main/src/openpifpaf/decoder/cifcaf.py#L119) for CifCaf decoder) and called ([here](https://github.com/vita-epfl/openpifpaf/blob/main/src/openpifpaf/decoder/cifcaf.py#L247) for CifCaf decoder) directly from the Python code.
