### ISSUE TITLE
why convert image to jpeg maybe good for detection?

### ISSUE THREAD

**Issue by flowtcw** [vita-epfl/openpifpaf#113]
@svenkreiss Hi, thank you for your amazing job. I have some confusion about **JpegCompression()** in **TRAIN_TRANSFORM**
https://github.com/vita-epfl/openpifpaf/blob/5f41cb496522dfe585de055b757f126840155bbb/openpifpaf/transforms.py#L471
In your code, you transform images to Jpeg and load it back to PIL_img. Can you give me some explanations about this?

**Comment by svenkreiss** [comment]
It's to add jpeg artifacts as a data augmentation. It seems to help when applying the models to other data sets that are heavily jpeg compressed.
