### ISSUE TITLE
No module named 'openpifpaf.functional'

### ISSUE THREAD

**Issue by nathanlem1** [vita-epfl/openpifpaf#12]
It generates this error: ModuleNotFoundError: No module named 'openpifpaf.functional'  Can you give any explanation pls? It seems it is not getting the C code.

**Comment by svenkreiss** [comment]
Strange, I would like to debug this. This is with the latest version? In Python 3? Also, sometimes it helps to do `pip install --upgrade pip setuptools`. Was there any error message during the installation of openpifpaf? Which OS?

This wouldn't be a general solution (you should not have to do this), but have you tried installing `pip install cython` before installing openpifpaf?

**Comment by www322** [comment]
Even I have installed Cython, I met this error too.  i solve it, but don't know why. 
solve by `pip install --editable '.[train,test]'`

**Comment by nathanlem1** [comment]
I tried on both Python3.5 and 3.7 on Ubuntu 16.04, and still it generates 'ImportError: No module named 'openpifpaf.functional' '

**Comment by svenkreiss** [comment]
Weird, those Python versions and this particular Ubuntu version are tested at every commit with our continuous testing: https://github.com/vita-epfl/openpifpaf/blob/master/.travis.yml

So you did this:
* cloned the repository
* `pip install --upgrade pip setuptools`
* `pip install --editable .`
* `pytest`

Which command produces the ImportError?

**Comment by www322** [comment]
I use python3.5,  did:

- cloned the repository

- `pip install --upgrade pip setuptools`---- my setuptools is newest, so i didn't do it

- `pip install openpifpaf`

- `pip install numpy cython`

- `python -m openpifpaf.predict \
  --checkpoint outputs/resnet101block5-pifs-pafs-edge401-l1-190131-083451.pkl \
  data-mscoco/images/val2017/000000081988.jpg -o docs/coco/ --show`
just the last step produces the importError @svenkreiss

**Comment by nathanlem1** [comment]
pip or pip3?

**Comment by svenkreiss** [comment]
@www322 Ok, you had conflicting versions of openpifpaf in your Python environment. When you did `pip install openpifpaf`, it uses a packaged version. You use this when you are __not__ cloning this repository. This is like installing any other Python package that you also don't need to clone (like numpy). I need to make this clear in the README.

When you then did `pip install --editable .`, the last dot stands for the local directory. So then you told Python to overwrite the packaged version from before and install the version that you have cloned to the local directory.

@nathanlem1 Does that help you, too?

**Comment by svenkreiss** [comment]
@nathanlem1 Good point. I generally work in virtual environments where pip means pip3 and python means python3, but if you want to make sure, be explicit and use pip3 and python3.

**Comment by www322** [comment]
oh, oh, i know, thanks very much, but can you share the /resnet101block5-pifs-pafs-edge401-l1-190131-083451.pkl in another way, for i can't access google drive

**Comment by www322** [comment]
> pip or pip3?

just use` python3 -m pip install ***`

**Comment by nathanlem1** [comment]
Now it is working, the @www322 's comment which is repeated below solved it:
I use python3.5, did:

cloned the repository

pip install --upgrade pip setuptools---- my setuptools is newest, so i didn't do it

pip install openpifpaf

pip install numpy cython

python -m openpifpaf.predict \ --checkpoint outputs/resnet101block5-pifs-pafs-edge401-l1-190131-083451.pkl \ data-mscoco/images/val2017/000000081988.jpg -o docs/coco/ --show
just the last step produces the importError @svenkreiss

But when i did pip install --editable '.[train,test]', then the last step, it's ok

Thanks guys!

**Comment by www322** [comment]
That's good, @nathanlem1 , but the correct way may be
First way (don't clone the repository)

- `python3 -m pip install openpifpaf`

- `python3 -m openpifpaf.predict \ --checkpoint outputs/resnet101block5-pifs-pafs-edge401-l1-190131-083451.pkl \ data-mscoco/images/val2017/000000081988.jpg -o docs/coco/ --show`

or the second way (clone the repository)  --

- clone the repository

- `python3 -m pip install --upgrade pip setuptools`

- `pip install numpy cython`

- `cd openpifpaf-master`
`python3 -m pip install --editable '.[train,test]'`

- `python3 -m openpifpaf.predict \ --checkpoint outputs/resnet101block5-pifs-pafs-edge401-l1-190131-083451.pkl \ data-mscoco/images/val2017/000000081988.jpg -o docs/coco/ --show`

**Comment by svenkreiss** [comment]
Glad it works now.

**Comment by mahdinobar** [comment]
Hello,

By running the command `python3 -m openpifpaf.predict \ --checkpoint outputs/resnet101block5-pifs-pafs-edge401-l1-190131-083451.pkl \ data-mscoco/images/val2017/000000081988.jpg -o docs/coco/ --show` **I get the same error `No module named 'openpifpaf.functional`.** 

I follow the steps bellow **with no error**.
- clone the repository
- python3 -m pip install --upgrade pip setuptools
- pip install numpy cython
- python3 -m pip install --editable '.[train,test]'

I use conda virtual environment with: 
- python version : 3.7.4.final.0

Please help me how to fix it.
