### ISSUE TITLE
Question about fill_coordinate function in encoder/pif.py

### ISSUE THREAD

**Issue by flowtcw** [vita-epfl/openpifpaf#120]
@svenkreiss I'm sorry to bother you. I have some confusion about keypoints convert to pif encoder. 

1. Why **side_length** need **subtract 1**. https://github.com/vita-epfl/openpifpaf/blob/bee5a08d9e9bd02963af55fd09e63e928943c6ff/openpifpaf/encoder/pif.py#L78 
https://github.com/vita-epfl/openpifpaf/blob/bee5a08d9e9bd02963af55fd09e63e928943c6ff/openpifpaf/encoder/pif.py#L120 In my opinion, I think `ij = np.round(xyv[:2] - (side_length / 2.0 ).astype(np.int) + self.padding` maybe right. _i.e._ ` self.s_offset = (side_length) / 2.0 `. Can you give me some explanations about this?
2. In `self.sink` https://github.com/vita-epfl/openpifpaf/blob/bee5a08d9e9bd02963af55fd09e63e928943c6ff/openpifpaf/encoder/pif.py#L77  https://github.com/vita-epfl/openpifpaf/blob/bee5a08d9e9bd02963af55fd09e63e928943c6ff/openpifpaf/utils.py#L28 The step in sink is 0.5, _e.g._ [ 1.5,  0.5, -0.5, -1.5]. I want to know how to calculate the step in feature map or the step maybe a hyper param? 
3. Another question is about **binary_erosion** https://github.com/vita-epfl/openpifpaf/blob/bee5a08d9e9bd02963af55fd09e63e928943c6ff/openpifpaf/encoder/pif.py#L93 What is the purpose of using this method?

Thank you very much!

**Comment by svenkreiss** [comment]
Thanks for your interest in OpenPifPaf.

1. This difference comes from the choice of coordinate systems. There is a difference between the total width of the feature map cells and the distance between the center of feature map cells. So if you have 4 feature map cells next to each other, the distance between the leftmost cell center and the rightmost cell center is only 3.
2. This relates to 1. The step length is one. It's just not on the integers.
3. This has to do with the fact that there are tiny crowd annotations in the COCO dataset. They are about the size of one feature map cell. But a single PIF activation is about 4 cells. So the erosion is the conservative estimate.

All the best for your project!
