### ISSUE TITLE
Question about decoding PIF, PAF

### ISSUE THREAD

**Issue by isht7** [vita-epfl/openpifpaf#126]
I have a question about the calculation of the high resolution fused PIF map. Thanks very much for your time.
The [high resolution fused PIF map is thresholded to get seed candidates here:](https://github.com/vita-epfl/openpifpaf/blob/master/openpifpaf/decoder/pif.py#L133-L134)
https://github.com/vita-epfl/openpifpaf/blob/d91552f11b47128714abde810df88865922fd4f8/openpifpaf/decoder/pif.py#L133-L134
 The high resolution map is created in [this line](https://github.com/vita-epfl/openpifpaf/blob/master/openpifpaf/decoder/pif.py#L102) of the corresponding for loop:
https://github.com/vita-epfl/openpifpaf/blob/d91552f11b47128714abde810df88865922fd4f8/openpifpaf/decoder/pif.py#L102
In [this function(quoted below)](https://github.com/vita-epfl/openpifpaf/blob/master/openpifpaf/functional.pyx#L80-L90), I expected the mean of the Gaussian to be shifted by the (x,y) position of the feature map because the arrow pointing towards the nearest joint originates from this position on the feature map. But upon reading the source of the function I found out that this is not the case and the Gaussian is not shifted. Why is this the case?
https://github.com/vita-epfl/openpifpaf/blob/d91552f11b47128714abde810df88865922fd4f8/openpifpaf/functional.pyx#L80-L90

**Comment by svenkreiss** [comment]
The decoder works with normalized PIF fields, ie check normalize_pif() in utils.py

**Comment by isht7** [comment]
That makes sense. Thanks for your reply. I was also wondering why you used this equation - 
https://github.com/vita-epfl/openpifpaf/blob/9988d9ac9fd9700ef4466d0332669c28e9512348/openpifpaf/decoder/pifpaf.py#L215
Is it to take care of some edge case?

**Comment by svenkreiss** [comment]
Yes. Strong PAF can still make a connection even for a weak PIF activation.

**Comment by isht7** [comment]
Thanks for your reply. 
Just out of curiosity: how do the 3 different connection_methods impact performance? (on say mscoco)
I believe you use 'max' to get the best results. How much degradation do you get with the other 2 methods? Does 'max' give best results on all datasets?
