### ISSUE TITLE
Why there is a variable 'force_complete_pose'?

### ISSUE THREAD

**Issue by yw155** [vita-epfl/openpifpaf#127]
Hi @svenkreiss, I have a question about the variable 'force_complete_pose'. When I disabled this variable, the accuracy of the model on the COCO dataset is decreased by around 10%. I would like to ask you why this variable has such a big effect on the accuracy. Thanks a lot.

**Comment by svenkreiss** [comment]
I saw that too and have been looking into this today.

To some extent this is natural for the COCO evaluation: COCO does not penalize for predicting extra keypoints. That means for `eval_coco` that it fills completely every pose. Guessing a wrong keypoint is not penalized. However, this is strange behavior for real-world applications so this is not the default when using `predict`.

The drop is still fairly large. Too large. I hope to have an update soon. For example, the default value for `--paf-th=0.1` seems large and you recover some of the performance by setting it to 0.01. But I suspect there is more.

**Comment by svenkreiss** [comment]
My conclusion for now is that the evaluation procedure of COCO just likes lots of false positives as long as they are ranked well. This is not what you want in most real world applications and therefore the difference in behavior/metric.
