### ISSUE TITLE
performance of block4 and block5

### ISSUE THREAD

**Issue by ll490187880** [vita-epfl/openpifpaf#136]
Hi, @svenkreiss ,
Is there any comparison of the performance of the resnet block4 and block5? Besides, how to use the dilated convolution in the source code?

**Comment by svenkreiss** [comment]
Current models all include block5. This is the standard ResNet. Leaving out block5 was an option at some point.

The options for dilated convolutions were also research options which I never got to work.

To be honest, I was considering to remove both the "block5" label (ie not allowing block4) and all options for dilated convolutions. But they also don't hurt.

**Comment by ll490187880** [comment]
So why not add an ablation study about the resolution before pifpaf process? I mean add the dilated convolutions or use resnet block4  to make a comparison.  
Besides, there are many options for training, but we do not known the effects of the options, will you add more descriptions for the options? Thank you.

**Comment by svenkreiss** [comment]
There is already an open issue (#119) to improve the documentation of the command line options. As a faster measure, I can look into tagging some command line options as experimental that I consider immature or that have never worked in practice (like dilation options).

Feel free to share any ablation study that you run and find interesting and it can be added to a documentation page.
