### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by kjjeong78** [vita-epfl/openpifpaf#141]
Hi. @svenkreiss,
I want to install the pifpaf.
pip3 install openpifpaf
then, i met the error:

ERROR: Could not find a version that satisfies the requirement torch>=1.1.0 (from openpifpaf) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.1.0 (from openpifpaf)

How can i solve this problem? please, help me.

**Comment by kjjeong78** [comment]
solved from this page
https://github.com/mindsdb/lightwood/issues/11

**Comment by svenkreiss** [comment]
I also had a temporary problem with pypi today and it solved itself.
Is there anything specific you had to do?

**Comment by kjjeong78** [comment]
If you got the message, then install the torch from conda in torch homepage.
I got the error with pypi install.
