### ISSUE TITLE
how to visualize PIF

### ISSUE THREAD

**Issue by flowtcw** [vita-epfl/openpifpaf#146]
Hi, @svenkreiss. I want to use your code to detect object keypoints. The object has no skeleton, so I just use the decoder/PIF.py. The code run successfully but the metric error is so high. I fund something: 1. Loss smoothed from 2 to around 0.05. I think that's right. 2. Each picture has only one identical object, regardless of the pre- or post-training period, class annotations I get are to much. In theory, only one annotation per image should be obtained.
In my opinion, the decoder maybe something wrong.  I want to solve the problem, so can you give me some advice to visualize PIF like Figure 3. in your paper.
![PIFregs](https://user-images.githubusercontent.com/28707142/65095815-4509dd00-d9f5-11e9-977e-b9f93661bb1b.png)
My english is not so good. So if you don't understand what I said, please tell me, I will try my best to explain that. Thank you very much!

**Comment by svenkreiss** [comment]
Hi @flowtcw , you can visualize the pif field with `--debug-pif-indices=5` (or any other keypoint index you like) in the predict and eval_coco scripts. Is that what you need?
