### ISSUE TITLE
the visualization of pif or paf  is good, but the total output is bad

### ISSUE THREAD

**Issue by ll490187880** [vita-epfl/openpifpaf#154]
Hello, @svenkreiss , when I visualize the pif or paf, the heat map looks good, but the total output is quite unacceptable. What should I do ? Which thresholds should be modified ?

**Comment by ll490187880** [comment]
OK , I have solved the problem.

**Comment by flowtcw** [comment]
Can you describe in detail what caused the problem?

**Comment by ll490187880** [comment]
@flowtcw . There is a variable named pif_nn in the decoding process. It will be used in the 'pif to pif_hr ' process. I did not use 17 keypoints, so pif_nn=16 is too large for me. I just reduced it. But I am not sure how to set the pif_nn, is it related to the number of keypoints?  Hello,@svenkreiss ,can you explain it?

**Comment by svenkreiss** [comment]
pif_nn is supposed to be the square of the pif-side-length you use used during training, which is 4 by default.
