### ISSUE TITLE
About the loss computation

### ISSUE THREAD

**Issue by yw155** [vita-epfl/openpifpaf#157]
Hi @svenkreiss, I would like to ask a question about the loss computation. I notice that the loss is divided by 1000 in loss.py. Why the loss computation need such a scale? In addition, is it need to divide by the channel number (e.g. joint number or limb number) in the loss computation? Thanks.

**Comment by svenkreiss** [comment]
A related question: why does everyone else divide by 1.0? Dividing by 1000 seems fine to me. There are many losses per image.

You could divide by the channel number, but I think adjusting lambda has the same effect.

**Comment by yw155** [comment]
Thanks for your reply.
