### ISSUE TITLE
Errors in colab demo 

### ISSUE THREAD

**Issue by Sierkinhane** [vita-epfl/openpifpaf#162]
---------------------------------------------------------------------------
      2 decode = openpifpaf.decoder.factory_decode(net, 
      3                                            force_complete_pose=False,
      4                                            seed_threshold=0.5)
      5 processor = openpifpaf.decoder.Processor(net, decode, 
      6                                          instance_threshold=0.2,
TypeError: __init__() got an unexpected keyword argument 'force_complete_pose'
----------------------------------------------------------------------------------------

---------------------------------------------------------------------------
     18   with openpifpaf.show.canvas() as ax:
     19     ax.imshow(im)
     20     skeleton_painter.keypoints(ax, keypoint_sets,scores=scores)
TypeError: keypoints() missing 1 required keyword-only argument: 'skeleton'
-----------------------------------------------------------------------------------

**Comment by svenkreiss** [comment]
Thanks. Should be fixed now.
