### ISSUE TITLE
Performance comparision (greedy.py)

### ISSUE THREAD

**Issue by isht7** [vita-epfl/openpifpaf#163]
This is not an issue with your code. In this [file](https://github.com/vita-epfl/openpifpaf/blob/master/openpifpaf/decoder/generator/greedy.py), you have 3 alternatives - 
* _target_with_median
* _target_with_maxscore
* _target_with_blend

I was hoping that you could tell how performance is affected(approximately) by using these 3 methods?

**Comment by svenkreiss** [comment]
Hello @isht7 , you can obtain these numbers by running `eval_coco` three times with the command line option `--connection-method` selecting one of the three methods that you mention. Please share the result here. Thanks!

**Comment by isht7** [comment]
Hi @svenkreiss, thanks for your reply. I evaluated the 3 options. These are the results I got
* blend 
![image](https://user-images.githubusercontent.com/21278652/67897848-701b3c80-fb1c-11e9-808c-5760dd674472.png)
* max
![image](https://user-images.githubusercontent.com/21278652/67897908-87f2c080-fb1c-11e9-9dac-ca151dfc6ff2.png)
* median 
![image](https://user-images.githubusercontent.com/21278652/67897937-9640dc80-fb1c-11e9-923d-c90d8403dfef.png)

**Comment by svenkreiss** [comment]
Thank you!
