### ISSUE TITLE
Rare pose and occluded  pose 

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#167]
thanks you for your paper
I have test on your repo and i saw your repo which failed with rare pose and occluded  pose, wrong connection associating parts from two persons.

**Comment by svenkreiss** [comment]
correct, it is not perfect.

**Comment by thanhtrung98** [comment]
Have you trained coco dataset + other data ( rare pose, occluded pose,...) yet?

**Comment by svenkreiss** [comment]
No, not yet, but that would be interesting to see.

**Comment by thanhtrung98** [comment]
I saw your train for coco dataset.
I want to train with coco data + other data
How to train on my own data?
Can you guide or provide code for me?
Thanks
