### ISSUE TITLE
No module named '__main__.network'; '__main__' is not a package

### ISSUE THREAD

**Issue by anuar12** [vita-epfl/openpifpaf#168]
I followed the commands to install after cloning the repository but when I run predict.py I get this error.
```Traceback (most recent call last):
  File "predict.py", line 15, in <module>
    from .network import nets
ModuleNotFoundError: No module named '__main__.network'; '__main__' is not a package```

**Comment by aalzooke** [comment]
I'm having the same issue 
```
Traceback (most recent call last):
  File "/home/intvo/Desktop/openpifpaf/openpifpaf/webcam.py", line 24, in <module>
    from .network import nets
ModuleNotFoundError: No module named '__main__.network'; '__main__' is not a package
```

**Comment by anuar12** [comment]
I am trying to run the file directly which creates a importing problem, if you install and run it in the way `www322` described it would work. 
https://github.com/vita-epfl/openpifpaf/issues/12

**Comment by aalzooke** [comment]
What commend did you use to run the predict file? Please share 
Thank you

**Comment by anuar12** [comment]
@aalzooke go to the link I shared, in the last post there is a last command by user `www322`
