### ISSUE TITLE
More information about generate PIF and PAF?

### ISSUE THREAD

**Issue by murdockhou** [vita-epfl/openpifpaf#17]
Hi, thanks for your work, it's impressive. But i still feel confusion about how to generate the `PIF` and `PAF` part, the source code in `openpifpaf/encoder/pif.py paf.py` is a little difficult for me to fully understand how it works. Could you please give more instructions about this part?
Thanks at all.

**Comment by www322** [comment]
i feel confused too, even i read the paper many times. can you give a deep and detailed explanation? @svenkreiss

**Comment by svenkreiss** [comment]
@murdockhou You are looking at the correct files. They generate the ground truth to learn by the network. Do you have more specific questions?

**Comment by www322** [comment]
I don't know what confused me , because all confused me , that's very terrible

**Comment by www322** [comment]
hello, can you give some annotation for your code, i really can't understand... @svenkreiss

**Comment by trungtpham** [comment]
Hi @svenkreiss  Thanks for the good work. I have a question about your vectorial ground truth encoding (p_x, p_y, p_b). Is [p_x, p_y] is a unit-norm vector and p_b is the magnitude?

Thanks,
Trung

**Comment by murdockhou** [comment]
Hi, @svenkreiss , your code is written so good that i need one by one to read your code and actually understand what that present. Could you please write some docs about how to generate pif and paf label or how to decode pif and paf label?  It's really difficult for me to re-write your code in C++ implementation. 
thanks,
matt

**Comment by murdockhou** [comment]
I have write some detailed information about pifpaf decoding process. Here is the [link](https://blog.csdn.net/Murdock_C/article/details/93748001), maybe somewhere is still wrong about that, please help me checking it out.

**Comment by dragonfly90** [comment]
@murdockhou, could you please describe a little about pif generator, such as the sink_reg and sink_l, If you get the point?

**Comment by murdockhou** [comment]
@dragonfly90  hi, in my opinion, the sink_reg is the area the one true joint point can locate, which means in this area, the whole label of intensity is 1. The sink_l is the conditions that decided the number of `fileds_reg`is. For example, if there are two joint point's `sink_reg` is crossed, then the number of the crossed area should be whose sink_l value is less.

**Comment by dragonfly90** [comment]
@murdockhou, I checked that the size of sink_reg is (2, 4, 4), so is it the positions of four boundary points?

**Comment by murdockhou** [comment]
@dragonfly90 4 only means the side length of label can present area. Not for four boundary points.

**Comment by dragonfly90** [comment]
@murdockhou, thanks. Do you try to use just pif, how is it compared to normal heatmap?

**Comment by murdockhou** [comment]
> @murdockhou, thanks. Do you try to use just pif, how is it compared to normal heatmap?

not yet.

**Comment by isht7** [comment]
Hi @svenkreiss,
In the function `fill_association` in paf.py, you have used,
``s_offset = (s - 1.0) / 2.0``,
``num = max(2, int(np.ceil(offset_d)))``,
``fmargin = min(0.4, (s_offset + 1) / (offset_d + np.spacing(1)))`` and
``frange = np.linspace(fmargin, 1.0-fmargin, num=num)``
Could you explain why each of these are defined in this way - I am not able to understand the reasoning behind these equations. Thanks!

**Comment by svenkreiss** [comment]
@isht7 These are used to create the area that is used as high confidence for PAF connections. It is sampling along the line between two joints and dealing with some corner cases (i.e. joints being very close together).

**Comment by isht7** [comment]
Hi @svenkreiss, thanks for the reply. I understand that `fields_reg_l` is probably used to have some policy for when the same point is inside the sink of 2 different interations in [this](https://github.com/vita-epfl/openpifpaf/blob/master/openpifpaf/encoder/paf.py#L166) `for` loop. Could you tell what is this policy / what cases is `fields_reg_l` supposed to handle?

**Comment by svenkreiss** [comment]
Hi @isht7. All correct. The policy is to give priority to the closest joint.

**Comment by isht7** [comment]
@svenkreiss  Thanks for your reply. It seems from the code that the line of high confidence for PAFs is the line joining the 2 joints but shifted by s_offset towards the origin (that is the line joining `joint1[:2] - s_offset` and `joint2[:2] - s_offset`). Why is this line shifted? Also it seems that the intermediate points on the line point towards `joint[:2] - s_offset` instead of `joint[:2]`. Why is that?

**Comment by ganler** [comment]
> > @murdockhou, thanks. Do you try to use just pif, how is it compared to normal heatmap?
> 
> not yet.

@murdockhou Hi, do you have any samples / reliable description about the decoding algorithm? I also find it is extremely hard to re-write the C++ codes, and I don't have enough time to sit down and do that...
