### ISSUE TITLE
Getting the Heatmap/Vector Field Output?

### ISSUE THREAD

**Issue by BK1024** [vita-epfl/openpifpaf#173]
Thank you for your great work in PIFPAF. Right now I am trying to apply the model to videos of infants (and I guess there were not many infants from the training set). To my surprise, it works fine on non-occluded infants. For occluded infants (by toy), the prediction is failing at non-occluded parts of the baby. I am trying to look deeper into this issue by visualizing the raw output from the model, the heatmap and the vector field, instead of the decoded and connected skeletons. Is there any option that allows me to get these outputs? I have gone over the help options for `openpifpaf.predict` and did not find anyone of them. Thank you!

**Comment by svenkreiss** [comment]
Yes, try `--debug-pif-indices=5 --debug-paf-indices=5`. All the best for
your project.

**Comment by BK1024** [comment]
I see. Thx!
