### ISSUE TITLE
The size of pif_hr mismatch the size of the image?

### ISSUE THREAD

**Issue by ll490187880** [vita-epfl/openpifpaf#175]
Hello,  @svenkreiss .  I found the two do not match when I print the shapes of the raw image and the pif_hr vector, e.g. (525, 800) and (513, 785). Thus, maybe it has some quadratuer error, this will influence the keypoint in the edge of the image.

**Comment by svenkreiss** [comment]
It's supposed to be like this when the size of the image cannot be filled with an integer number of convolutions of the output stride.
