### ISSUE TITLE
mask miss for mpii

### ISSUE THREAD

**Issue by Sierkinhane** [vita-epfl/openpifpaf#18]
Could you tell me how to evade a few of people unannotated in an image？emm... like mask miss？

**Comment by Sierkinhane** [comment]
or the way you process the unannotated keypoints of people in an image

**Comment by svenkreiss** [comment]
Only COCO is supported for training right now and it contains crowd annotations (masks that indicate that this region could contain keypoints that are not annotated).

**Comment by Sierkinhane** [comment]
Yes, I trained a bottom-up pose network  on coco using mask miss generated by open pose repository. And I want to train it on mpii, yet confusing how to evade those unannotated person in an image. Now, I just train it on single person dataset of mpii. Will you train pifpaf network on multi-person dataset of mpii?

**Comment by Sierkinhane** [comment]
It seems that it's not a problem for top-down methods.

**Comment by Ivamcoder** [comment]
Hi @Sierkinhane 

Have you found answer about masking unlabeled people in MPII dataset for bottom up approach?

**Comment by Sierkinhane** [comment]
@lvamcoder yes. http://posefs1.perception.cs.cmu.edu/Users/ZheCao/masks_for_mpii_pose.tgz this is mask for mpii and json http://posefs1.perception.cs.cmu.edu/Users/ZheCao/MPI.json. there are some bugs in mask and json. You should try to fix it.

**Comment by Sierkinhane** [comment]
@Ivamcoder

**Comment by Ivamcoder** [comment]
Thank you so much @Sierkinhane

**Comment by KevinHexin** [comment]
> @Ivamcoder
hi, did your trained the model in MPII dataset?
