### ISSUE TITLE
Incorrect field length while evaluating after training

### ISSUE THREAD

**Issue by sg-pillai** [vita-epfl/openpifpaf#184]
Thank you for your great work! I have modified the dataloader part to try with my dataset. I tested the training part successfully with few images. I trained with the headnets (pif pafs) and for other headnets assertion error for the length of target is throwing in the forward function of composite loss (due to the mismatch in n_scales and n_vectors). 
Now I am trying to evaluate and there is no entry for the headnet 'pafs' in the decoder factory, hence I had to add it. But now I am getting an error while trying to evaluate:

TypeError: normalize_paf() takes 5 positional arguments but 7 positional arguments (and 1 keyword-only argument) were given

This is due to the fact that the length of fields for 'paf' at the paf_index is coming as 7 and the normalize_paf() function takes only 5 positional arguments. normalize_pif() is executing properly. I tested with coco dataset also and the same issue is there. Hence I believe that it's not due to my new dataset and the modifications done as part of it. I believe this issue is valid only for the latest version since the changes related to loss parameters are only in the latest version.

I would be really glad if you could give me some insight into this issue.

Thanks a lot

**Comment by zechendev** [comment]
I have the same problem!

**Comment by svenkreiss** [comment]
Hello, please use `paf` not `pafs` as the name for your head network.

**Comment by sg-pillai** [comment]
Hi @svenkreiss ,
Thank you for your reply. When I am using pafs as headnet assertion error for the length of the target is throwing in the forward function of composite loss.
I verified in version 9 and it is working fine in that version. In version 9 I can use headnet 'pif paf'. I just modified the code in the evaluation as a workaround and I am getting over it for now. But the error is not fixed.
Thanks!!

**Comment by zechendev** [comment]
> Hello, please use `paf` not `pafs` as the name for your head network.

Hi, I have modify the code with 'pif paf', but the problem is still there.

**Comment by sg-pillai** [comment]
> > Hello, please use `paf` not `pafs` as the name for your head network.
> 
> Hi, I have modify the code with 'pif paf', but the problem is still there.

Hi @zechendev ,
When you use headnets 'pif paf' in version 10, are you getting any assertion error with respect to the length of the target in the forward function of composite loss?

openpifpaf-master/openpifpaf/network/losses.py", line 249, in forward
    assert len(t) == 1 + self.n_vectors + self.n_scales
AssertionError

**Comment by zechendev** [comment]
> > > Hello, please use `paf` not `pafs` as the name for your head network.
> > 
> > 
> > Hi, I have modify the code with 'pif paf', but the problem is still there.
> 
> Hi @zechendev ,
> When you use headnets 'pif paf' in version 10, are you getting any assertion error with respect to the length of the target in the forward function of composite loss?
> 
> openpifpaf-master/openpifpaf/network/losses.py", line 249, in forward
> assert len(t) == 1 + self.n_vectors + self.n_scales
> AssertionError

Yse, I did not use the default setting in the document, instead using " --headnets pif paf \", also the  AssertionError occurs. 
I also search the Issuses, found that the version 9 maybe a stable version. You may try it.

**Comment by svenkreiss** [comment]
You cannot use a checkpoint that you trained with `pafs`. 
You need to train a new model where you use `paf` and then evaluate that model.

PR #185 adds a check that a model created with `--headnets pif paf` can be evaluated. And it does pass.

**Comment by sg-pillai** [comment]
@svenkreiss Yes, I did not use a checkpoint that I trained with pafs. 
Even when I am training a new model using --headnets pif paf , the error is coming.
here is a command which i used to test it:
CUDA_VISIBLE_DEVICES=5 python3 -m openpifpaf.train   --lr 1e-3   --momentum 0.95   --headnets pif paf   --epochs 50   --lr-decay 60 70   --batch-size 8   --basenet resnet50   --head-quad 1 -o pifpafv10 --lambdas 2 2 50 3 3 50 3 3

**Comment by sg-pillai** [comment]
> > > > Hello, please use `paf` not `pafs` as the name for your head network.
> > > 
> > > 
> > > Hi, I have modify the code with 'pif paf', but the problem is still there.
> > 
> > 
> > Hi @zechendev ,
> > When you use headnets 'pif paf' in version 10, are you getting any assertion error with respect to the length of the target in the forward function of composite loss?
> > openpifpaf-master/openpifpaf/network/losses.py", line 249, in forward
> > assert len(t) == 1 + self.n_vectors + self.n_scales
> > AssertionError
> 
> Yse, I did not use the default setting in the document, instead using " --headnets pif paf ", also the AssertionError occurs.
> I also search the Issuses, found that the version 9 maybe a stable version. You may try it.

Hi @zechendev ,

okay. Yes, I am already trying it in version 9 where I am not facing this issue.

**Comment by anant15** [comment]
I am still struggling with this error. Please let us know the solution for version 10 as I need use the Resnet18 for which I couldn't see the support in version 9.
