### ISSUE TITLE
Unable to convert OpenPifPaf model using torch2trt

### ISSUE THREAD

**Issue by magdalena-dd** [vita-epfl/openpifpaf#188]
Hi, I tried to run torch2trt conversion of OpenPifPaf model inside TensorRT Docker image (tensorrt:19.12-py3) and I get the following error:

```
Traceback (most recent call last):
  File "scripts/test_torch2trt.py", line 17, in <module>
    model_trt = torch2trt(model, [x])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 381, in torch2trt
    ctx.mark_outputs(outputs, output_names)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 282, in mark_outputs
    trt_tensor = torch_output._trt
AttributeError: 'list' object has no attribute '_trt'
```

Environment inside Docker container:

- Ubuntu 18.04 
- Python 3.6.9
- CUDA 10.2.89 
- TensorRT 6.0.1

`test_torch2trt.py` script that produces the error:
```
import torch
import openpifpaf
from torch2trt import torch2trt


model, _ = openpifpaf.network.factory(
        base_name='resnet18',
        head_names=['pif', 'paf'],
        pretrained=False,
    )
model.eval().cuda()

# create dummy data
x = torch.ones((1, 3, 240, 320)).cuda()

# convert to TensorRT feeding sample data as input
model_trt = torch2trt(model, [x])
```

Dockerfile:
```
FROM nvcr.io/nvidia/tensorrt:19.12-py3

# install openpifpaf
RUN git clone https://github.com/vita-epfl/openpifpaf.git && cd openpifpaf && python setup.py install

RUN pip install --upgrade Cython
RUN pip install torch torchvision matplotlib numpy pycocotools

# install torch2trt
RUN git clone https://github.com/NVIDIA-AI-IOT/torch2trt && cd torch2trt && python setup.py install
```

**Comment by thancaocuong** [comment]
torch2trt does not support list of tensor as output of model. So if you want to convert pytorch model to trt model, you need to modify forward function to return only last stage output (It's easy when you have the pretrained model, so you only need output of last stage).

**Comment by gondimjoaom** [comment]
does anyone has any news about this?

**Comment by thancaocuong** [comment]
@gondimjoaom  should we develop the tensorRT branch for openpifpaf? It should quite interesting

**Comment by svenkreiss** [comment]
Hello @thancaocuong (cc @gondimjoaom @magdalena-dd ), that would be great!

I would like to point out some work I have done recently (even yesterday) in the `dev` branch. This branch is a major rewrite of the head architecture removing many reshape and slice operations that were previously there. Yesterday, I have added a unit test that closes the loop: take an OpenPifPaf model, run prediction with OpenPifPaf, export that model to onnx, run prediction of onnx model with onnxruntime, compare output of both predictions. The dev branch has a resnet50 and a shufflenetv2k16w pretrained so far. Can someone check whether that improved compatibility with tensorrt?

**Comment by thancaocuong** [comment]
@svenkreiss I will check it later and give you what I find.

**Comment by svenkreiss** [comment]
Thank you @thancaocuong !

**Comment by thancaocuong** [comment]
@svenkreiss Converting from onnx -> tensorrt is oke. But the inference result has some difference (max (i,j) L1 is 0.05). So I will dig into this problem and report later.

**Comment by svenkreiss** [comment]
Great news @thancaocuong  that the conversion to tensorrt worked now. Max L1 difference of 0.05 is a bit large to just be numerical error but also small enough to indicate that it is working in general. Could be input normalization or something like that. Thanks for digging into that!

**Comment by gondimjoaom** [comment]
Hey, guys! Great news indeed! I've trained openpifpaf with my own custom data and some colleagues are on the task of converting either the .pkl or .onnx model. Any news on that and we sure add here. They are following this thread. I used shufflenet as backbone to create my model, and I'm know on my way to train a new one resnet50 based as I've been told it might be better for working on the conversion.

**Comment by thancaocuong** [comment]
@gondimjoaom I've converted  resnet50 and shufflenetv2k16w backbone, but it doesnt pass the test (losses are too high). Could you show more details about your works?

**Comment by gondimjoaom** [comment]
@thancaocuong so, one of my colleagues converted the openpifpaf resnet50 to onnx and later to tensorrt and is having these results when running inferences:
![i4](https://user-images.githubusercontent.com/29072586/93475889-874b5000-f8cf-11ea-949a-2e0938990efd.png)
![i3](https://user-images.githubusercontent.com/29072586/93475890-887c7d00-f8cf-11ea-9823-6d48b1fae2d2.png)
![i2](https://user-images.githubusercontent.com/29072586/93475893-89151380-f8cf-11ea-85e1-f2cf42689d6c.png)

**Comment by svenkreiss** [comment]
When switching branches on a checkout of the repository, make sure to rerun `pip install -e .` to recompile the cython code. 
It seems like something isn't right how the offset is converted to absolute coordinates and if I remember correctly that changed between branches.

**Comment by thancaocuong** [comment]
@svenkreiss I've found that these two model (resnet and shuffle) both have some inplace operations such as sigmoid_, add_,... . So could you replace it? I use torch2trt to convert pytorch model directly but encountered some unsupported method.

**Comment by svenkreiss** [comment]
Yes, that is done already in the dev branch.

You can run torch2trt without exporting to onnx? I am not familiar with TensorRT.
If you do that and have your own script, you need to switch off the "inplace_ops" as in the export_onnx script: `openpifpaf.network.heads.CompositeField3.inplace_ops = False`

**Comment by thancaocuong** [comment]
@svenkreiss  hot news, I modify some logic in forward function of heads net. And now I can convert resnet50 backbone model with the loss L1 max around 4.4107e-06.

**Comment by svenkreiss** [comment]
Fantastic @thancaocuong ! I hope you can share with us soon the important change to make it work ...

**Comment by thancaocuong** [comment]
@svenkreiss 
* change https://github.com/vita-epfl/openpifpaf/blob/ef6a6f37cae08a6eb6cbeac0cf8040490a1cad19/openpifpaf/network/heads.py#L236 to 
```x = torch.transpose(x, 1, 2)```
* change https://github.com/vita-epfl/openpifpaf/blob/ef6a6f37cae08a6eb6cbeac0cf8040490a1cad19/openpifpaf/network/heads.py#L266 to 
```x = torch.transpose(x, 1, 2)```
* change https://github.com/vita-epfl/openpifpaf/blob/ef6a6f37cae08a6eb6cbeac0cf8040490a1cad19/openpifpaf/network/heads.py#L250-L251
to 
```
for i, (reg_x, do_offset) in enumerate(zip(regs_x, self.meta.vector_offsets)):
    if do_offset:
        reg_x = torch.add(reg_x, index_field)
    regs_x[i] = reg_x
```
Finally, use torch2trt to convert model to TensorRT, but remember to set inplace_ops to False with ```openpifpaf.network.heads.CompositeField3.inplace_ops = False
```

**Comment by thancaocuong** [comment]
Currently I can convert only resnet50 backbone. Shufflev2 backbone has the shufflePixel layer that does not supported by TensorRT (torch2trt). So I will try to implement it and share to you if it works

**Comment by svenkreiss** [comment]
Thanks @thancaocuong ! I would not have guessed that ‘torch.op’ versus ‘tensor.op’ makes that difference. I don’t have a problem switching to ‘torch.op’ at all. Do you know why that makes a difference? Is there a discussion somewhere on the web that clarifies this?

**Comment by thancaocuong** [comment]
I think that it depends on the way torch2trt use to convert dynamic graph framework(pytorch)  to static graph(tensorRT). Let me check the torch2trt source to see what's the limitation.

**Comment by svenkreiss** [comment]
Thanks for looking into that. I am quite curious as to what is the reason.

Do you want to submit a short pull request against dev with these three lines of changes? I would need a signed CLA document from you (see "contribute" in the guide) to become a contributor.
Otherwise I can also prepare a pull request.

If you do prepare the PR, for your third change, can you keep it as a list comprehension and just change the op?

**Comment by thancaocuong** [comment]
@svenkreiss Thank you, I will create a pull request for these change. For the third change, I will keep it as a list comprehension.  Anyway, I have plan to develop a C++ branch for TensorRT inference and try to optimize some preprocessing and post-processing steps to obtain the high performance inference on edge devices such as Nvidia Jetson

**Comment by svenkreiss** [comment]
That's great @thancaocuong . For TensorRT inference, this code might be helpful: https://github.com/vita-epfl/openpifpaf/tree/master/cpp/examples/cifcafdecoder (again, I am not a TensorRT expert but it seems useful). However, this code is outdated for a few versions now but seems well written.

**Comment by svenkreiss** [comment]
I am closing this for now. Feel free to open new issues.
