### ISSUE TITLE
Incorrect field length while evaluating after training

### ISSUE THREAD

**Issue by anant15** [vita-epfl/openpifpaf#189]
I am still getting this error in the latest release when I am trying to train a ResNet 18 model be it on COCO data or my own custom data. Kindly suggest a concrete solution besides using version 9 as it doesn't support Resnet18, and it isn't the easy to add compatibility for that as it seemed.

**Comment by svenkreiss** [comment]
Thanks for your patience. I have opened a pull request that not only fixes this bug, but it also adds a substantial unit test that will run for all future commits.

In the future, a new model will be trained every time. To make that feasible with small compute resources, it will train a ResNet18 for one step on a single image. It will use the standard command line interface to run this training step. Then, it will take this trained model and predict a pose skeleton. Again, it will use the standard command line tool. Then it will check whether a json file with the pose skeletons was created. No useful skeleton will come from this, but it will check that the whole pipeline from training from scratch to prediction is working. 

I hope this will solve the issue that you saw.

**Comment by anant15** [comment]
This now leads to an assert error at line 131 in losses.py. 

```assert len(self.losses) == len(head_fields)```
