### ISSUE TITLE
Method of pifpaf

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#199]
Hi
I have some question about paper
In paper, I don't understand scale σ in Part Intensity Fields. What is the scale σ?
<img width="567" alt="Screen Shot 2020-04-27 at 15 32 32" src="https://user-images.githubusercontent.com/43095377/80351309-54f77280-889c-11ea-968b-e6db5a6f1afe.png">

**Comment by svenkreiss** [comment]
It's an estimate of the size of the joint as defined in the COCO annotations and where it is used for the OKS score.
