### ISSUE TITLE
Cannot install with Torch 2.1.1, cpp extension undefined symbol

### ISSUE THREAD

**Issue by kikohs** [vita-epfl/openpifpaf#20]
I'm trying to install with Torch 2.1.1, I remember it working with the nightly.
Here is the error:

```
OSError: /home/kirell/.cache/pypoetry/virtualenvs/emv-IgKv7S_O-py3.10/lib/python3.10/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN3c104impl12PyObjectSlotD1Ev
b
```

**Comment by taylormordan** [comment]
What commands did you run? If you've updated PyTorch, you should recompile (pip install) OpenPifPaf.

**Comment by kikohs** [comment]
I've spent the past 3 hours on this:

The issue is that the wheel online is broken.
First install pytorch (works with 2.1.1 now).

Then:
```pip uninstall -y openpifpaf-vita && pip install --no-build-isolation --no-binary=openpifpaf-vita openpifpaf-vita```

For poetry users:

```
poetry config --local installer.no-binary openpifpaf-vita
poetry add openpifpaf-vita
```
