### ISSUE TITLE
Question about score field in JSON output

### ISSUE THREAD

**Issue by javierlorenzod** [vita-epfl/openpifpaf#200]
Hi,

I am trying to figure out the origin of the **score** field in the JSON output dictionary of pifpaf network. At first, I thought about the mean or the median of keypoints scores, but I calculated them and both are different. In your paper, you said that for COCO submission you need a score for each keypoints in the pose and one for the whole pose, but I have not found the way to obtain it either. Could you please explain to me how to get it?

Thank you, and thanks for making your work public!

**Comment by svenkreiss** [comment]
The evaluation on the validation set is a bit sensitive to that exact score calculation, so I have adapted it over time. The calculation is here:
https://github.com/vita-epfl/openpifpaf/blob/master/openpifpaf/decoder/annotation.py#L44
and the score weights are setup in the constructor above.

**Comment by javierlorenzod** [comment]
Ok, it is crystal clear now. Thanks for your help.
