### ISSUE TITLE
Head nets

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#201]
Hi!
I have a question about head nets.
I don't understand PixelShuffle and upscale_factor
what is upscale_factor?
what it PixelShuffle?
if I change the value of upscale_factor, Will it be changed?
<img width="588" alt="head_net" src="https://user-images.githubusercontent.com/43095377/81634334-f3f1a200-9438-11ea-922b-2e7d5aa30844.png">

**Comment by svenkreiss** [comment]
Hi @thanhtrung98 , PixelShuffle is the standard PyTorch module:
https://pytorch.org/docs/master/generated/torch.nn.PixelShuffle.html
This page also contains a link to the paper on subpixel convolutions.
