### ISSUE TITLE
Question about detailed method reference of the paper 

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#202]
Hello,

I have been following and reading your paper "PifPaf: Composite Fields for Human Pose Estimation". I am a senior now, doing my bachelor thesis. I need to to understand more about the paper, especially the method. Are there any detailed documents that I can refer to or is there an available journal version of the paper ?

**Comment by svenkreiss** [comment]
Unfortunately, we do not have a longer version than the published paper.
