### ISSUE TITLE
Error: CUDA out of memory and assertion error

### ISSUE THREAD

**Issue by akshaism** [vita-epfl/openpifpaf#204]
Hello @svenkreiss ,
I am trying to start the training of openpifpaf model on 17 key points , whereas , my dataset is labeled with 11 keypoints i.e. for nose, eyes, ears, shoulders, elbows , wrists (both left and right). But I have added zeros to represent the remaining 6 keypoints i.e. hips, knees, ankles (both left and right). It successfully creates the train.json and required files for training, when I try to start the training , it gives me following errors:
`RuntimeError: CUDA out of memory. Tried to allocate 316.00 MiB (GPU 0; 7.93 GiB total capacity; 7.12 GiB already allocated; 114.38 MiB free; 7.14 GiB reserved in total by PyTorch)`

after running it again it gives me error:
`assert len(t) == 1 + self.n_vectors + self.n_scales
AssertionError`

I am using openpifpaf version = 0.10.1

How can I resolve this ? Do I need to use the latest version or is there any other way that I can make it use the custom skeleton keypoints (11 key points)?

**Comment by svenkreiss** [comment]
Hi @akshaism 

The out of memory error happens when someone else or another process is already using your GPU.

The AssertionError afterwards is where something in your modifications to OpenPifPaf goes wrong. I have only seen that error when there was a bug somewhere else. Maybe in the encoder?

**Comment by akshaism** [comment]
Hello @svenkreiss , thank you so much for your reply.
Yes, I did check the GPU processes , currently there aren't any consuming GPU. 
I tried to change the batchsize to 6 or even 4 , and the AssertionError is thrown
In the /network , I checked into losses.py  where the error points to :

`File "/home/ben/anaconda3/envs/openpifpaf/lib/python3.7/site-packages/openpifpaf/train.py", line 199, in main
    trainer.loop(train_loader, val_loader, args.epochs, start_epoch=start_epoch)`
` File "/home/ben/anaconda3/envs/openpifpaf/lib/python3.7/site-packages/openpifpaf/network/losses.py", line 134, in forward
    for l, f, t in zip(self.losses, head_fields, head_targets)
  File "/home/ben/anaconda3/envs/openpifpaf/lib/python3.7/site-packages/openpifpaf/network/losses.py", line 135, in <listcomp>
    for ll in l(f, t)]`
`File "/home/ben/anaconda3/envs/openpifpaf/lib/python3.7/site-packages/openpifpaf/network/losses.py", line 238, in forward
    assert len(t) == 1 + self.n_vectors + self.n_scales
AssertionError`

Also , do you think upgrading openpifpaf version might resolve this issue ? as I noticed that pif and paf has been changed to cif and caf respectively in openpifpaf version: 0.11.1, does that need to be update my current openpifpaf library package ?

**Comment by svenkreiss** [comment]
This assert error is not about GPU memory. That was your previous error message.

Unfortunately, the stack trace is not giving much information. This only shows that the loss gets the wrong kind of input. One of the inputs is the neural network output and the other input is the output of an encoder. 

It's hard for me to tell you whether you will have less problems with v0.11. There is a big refactor in v0.11 that should make it much easier to adapt it for new kinds of keypoints and skeletons. If that is the only thing you are changing, than in v0.11, you only need to touch the `openpifpaf/datasets` folder. You should not have to modify losses and encoders anymore.

**Comment by MoonBunnyZZZ** [comment]
> Hi @akshaism
> 
> The out of memory error happens when someone else or another process is already using your GPU.
> 
> The AssertionError afterwards is where something in your modifications to OpenPifPaf goes wrong. I have only seen that error when there was a bug somewhere else. Maybe in the encoder?

Hi @svenkreiss  @akshaism 
In version 0.10.1, there is a func,named loss_parameters, in network/loss.py. 
It returns a dict about number of  vectors and scales.
When training a net with argument headnets which is "pif paf paf25" (net with resnet as backbone using this argument), this func will return dict {'n_vectors': 2, 'n_scales': 0} for argument paf. So, the assertion error occur.

I check the training logs of  resnet18,resnet50,resnet101.All of them using "pif paf paf25" for arguments headnets.

Do I miss something important?If not, how to do with the bug?

**Comment by svenkreiss** [comment]
This has been fixed a while ago. Please use a newer version.
