### ISSUE TITLE
Question about loss function

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#208]
Hi you!
I have some question about your paper.
In Section 3.4, I don't understand spread b. what is the spread b?
In loss function, if b increases loss will decrease and Reverse. why did you use log() in loss function? 
<img width="595" alt="Screen Shot 2020-05-22 at 10 21 25" src="https://user-images.githubusercontent.com/43095377/82628636-8c490d00-9c17-11ea-9c7a-64d3eb8fab49.png">

**Comment by svenkreiss** [comment]
Please see reference 23 that explains this type of loss in detail.

**Comment by thanhtrung98** [comment]
Hello @svenkreiss , thank you so much for your reply.

**Comment by thanhtrung98** [comment]
Hi!
I saw in your paper "new composite field PAF encoding fine-grained" in Abstract but I read section 3.3 Part Association Fields and I didn't talk about it. Can you explain detail about "fine-grained in PAF"?
<img width="459" alt="Screen Shot 2020-05-23 at 15 26 19" src="https://user-images.githubusercontent.com/43095377/82725802-c5fa4080-9d09-11ea-91fd-77ce19b2d354.png">

**Comment by svenkreiss** [comment]
Our PAF has floating point precision. It originates at a feature cell, but the two points that it associates have floating precision. Other methods are more coarse because they do contain some form of feature cell discretization.
