### ISSUE TITLE
spread b

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#215]
Hi!
I read section 3 and I didn't understand spread b. what is spread b?
I saw use spread b in section 3.1 Part Intensity Fields but In section 3.2 Part Association Fields, you use width b? 
<img width="1006" alt="Screen Shot 2020-05-24 at 14 27 31" src="https://user-images.githubusercontent.com/43095377/82748319-184f6600-9dcb-11ea-9a33-6148ff36e977.png">

**Comment by svenkreiss** [comment]
We should have used "spread b" in section 3.3 to make it more clear. Both are the extra parameter that is needed for the Laplace loss.

**Comment by svenkreiss** [comment]
I pressed the wrong button. 

Let me know if still unclear.

**Comment by thanhtrung98** [comment]
Can you explain detail about spread b?

**Comment by svenkreiss** [comment]
It's the same b as in the Laplace loss:

![image](https://user-images.githubusercontent.com/2775078/82749663-0f4e9c80-9dab-11ea-847c-81b2d0ff7f62.png)

More details and motivation are in:

![image](https://user-images.githubusercontent.com/2775078/82749696-43c25880-9dab-11ea-887c-f92ae26f19a1.png)

**Comment by thanhtrung98** [comment]
thank you so much for your reply

**Comment by thanhtrung98** [comment]
I saw in your pipeline, Input is color Image (3 Chanels), but I didn't see what is output?
Output is the same input (color image with 3 Chanels)?

**Comment by svenkreiss** [comment]
The output of the decoder is a data structure that has for every person 17x3 entries which are (x,y,confidence) of every joint.
