### ISSUE TITLE
Question about table 1 in paper

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#217]
<img width="1213" alt="Screen Shot 2020-05-26 at 16 01 14" src="https://user-images.githubusercontent.com/43095377/82881823-68186380-9f6a-11ea-8ee9-0e8cbfab5697.png">
Hi!
I have a question about your paper
What is the long side equal to 321px?
Did you resize image to 321px?

**Comment by svenkreiss** [comment]
Yes. Resize image such that long side = 321px.
