### ISSUE TITLE
readme -> video section command is wrong

### ISSUE THREAD

**Issue by Humphreybas** [vita-epfl/openpifpaf#218]
I was thinking about making a merge request for this but since I have never done it, and signing license papers for these tiny tiny changes to the readme I figured I better just suggest one of the existing contributors to change it:

The video section in the readme could be slightly improved by making it into this:

```
\# Video

Requires OpenCV and Matploblib.

\```sh
python3 -m openpifpaf.video --checkpoint shufflenetv2k16w --source=myvideotoprocess.mp4 --video-output --json-output
\```

``` 

(Added `--source=` and Matplotlib dependency.)

**Comment by svenkreiss** [comment]
Thanks for spotting and suggesting the change! 
All the best for your project.
