### ISSUE TITLE
Dimension Change from shufflenet output to CIF (1, 17, 5, 14, 18) to (1, 17, 5, 13, 17)

### ISSUE THREAD

**Issue by nishgaba-ai** [vita-epfl/openpifpaf#219]
**Review of shufflenet2k16 base output**
After the conversion of shufflenet2k16 checkpoint to onnx and also reviewing the original code, the output comes to be shaped: (for inputs of [1, 3, 97, 129 )
**[1, 1392, 7, 9]**
When passed into **CompositeFieldFused** for CIF after convolution(changes shape to [1, 340, 7, 9]),
and Pixelshuffle (the dimensions are changed to **[1, 85, 14, 18]**) the data is then sliced into 4, and finally concatenated after the respective operation on each slice. 

The output shape after such rearrangement was expected to be:

**[1, 17, 5, 14, 18]**
but the actual output occurring in the graph is:
**[1, 17, 5, 13, 17]**

What's the reason behind such change and which operation is causing this, as onnx graph only mentions, reshape and concatenation operations (and corresponding "view" operations in the original code files).
![Selection_285](https://user-images.githubusercontent.com/30121375/83308973-a8efd100-a225-11ea-958a-431c74a20fa8.png)
![Selection_284](https://user-images.githubusercontent.com/30121375/83308977-abeac180-a225-11ea-81fb-f1e375ed8336.png)

**Comment by svenkreiss** [comment]
Hello @nishgaba-ai , did you manage to get a working ONNX export?

**Comment by nishgaba-ai** [comment]
Yes, @svenkreiss I found the code, removing that 1 index.
Managed to port the architecture to Tensorflow2 using the onnx graph and code files.
Thanks for the great work.
