### ISSUE TITLE
Significance of process head  - CifCaf

### ISSUE THREAD

**Issue by rlrahulkanojia** [vita-epfl/openpifpaf#226]
The checkpoints (shufflenet 2k16w) given contain the process head as cifcaf collector but the help train command doesn't illustrate and process head.
If trained without and process head, how can the results be visualized?

**Comment by svenkreiss** [comment]
I am not sure I understand the question. CifCafCollector is deterministic and does not need to be trained. Use `--debug-images` together with `--debug-indices cif:5 caf:5` to see some debug images during training or prediction.

**Comment by rlrahulkanojia** [comment]
I came around that, Thank you for answering.
