### ISSUE TITLE
question about evaluation ?

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#230]
Hi
I have a question about paper
How much did you resize image in table 1?
I don't understand "the long side equal 321px"
I think it's mean if the height > width , image will resize the height to 321px and the width don't change. if width >height, image will resize the width to 321px and the height don't change.
<img width="949" alt="Screen Shot 2020-06-05 at 11 04 30" src="https://user-images.githubusercontent.com/43095377/83835955-5aa66a80-a71c-11ea-9496-50abcecb6462.png">

**Comment by svenkreiss** [comment]
No, the aspect ratio of the image is kept.
