### ISSUE TITLE
pixel position of key points

### ISSUE THREAD

**Issue by mohammad-saber** [vita-epfl/openpifpaf#232]
Thank you very much for sharing your great work. 

My question is that how I can get the pixel position of detected key points when I run "openpifpaf.predict".

Thanks.

**Comment by svenkreiss** [comment]
It's in the json output: https://vita-epfl.github.io/openpifpaf/predict_cli.html
Under "keypoints", you get all the pixel coordinates in COCO format: x,y,c for all the 17 joints.

**Comment by mohammad-saber** [comment]
Thank you. 

When I check pixel values, they are not integer values. Should I round them?

And, when the pixel value is 0 or negative, does it mean it was not detected?

**Comment by svenkreiss** [comment]
It's in pixel coordinates with sub-pixel accuracy. 10.5 simply means the joint is between pixel 10 and 11.

Sometimes, joints can be localized outside the field of view and then the values can be negative. Threshold the third number, the confidence, to filter for not detected joints.

**Comment by mohammad-saber** [comment]
Thank you. 

When there are several persons in the image, How do I understand which Key-points belong to which person?

I think Face Recognition is not the purpose of your project. 

It seems the only way is using bounding box, and the location of every person in the image.

**Comment by svenkreiss** [comment]
No. You get multiple annotations in the json. 

The first "keypoints" entry is for the first person (https://vita-epfl.github.io/openpifpaf/predict_cli.html):
![image](https://user-images.githubusercontent.com/2775078/84246632-2d383300-ab07-11ea-8af9-e39d977be8eb.png)

But then if you scroll down, you see there are 5 of those entries. This is where one entry ends and the entry for the next person starts with a new set of "keypoints":
![image](https://user-images.githubusercontent.com/2775078/84246739-535dd300-ab07-11ea-8a13-6f06aa076fe2.png)

**Comment by mohammad-saber** [comment]
Thank you. 

Is there any order when it is said the 1st person or 2nd person?

For example, from left to right?

**Comment by svenkreiss** [comment]
No, I believe it is order by "score", but that is not guaranteed.

You can order it yourself. To get a rough left to right order, you could use the first entry in "bbox" which is the x-coordinate of the left-side of the bbox and sort by that.

**Comment by mohammad-saber** [comment]
thank you for your time. 

you have provided an example on colab: 

https://colab.research.google.com/drive/1H8T4ZE6wc0A9xJE4oGnhgHpUpAH5HL7W

When I run this code, I get the predictions. 
How can I get Jason output (including bounding box & body joints pixel position) from the above code?
Is Jason output only obtained when I run the code from terminal?

**Comment by svenkreiss** [comment]
Take a look at the `predictions` variable:
![image](https://user-images.githubusercontent.com/2775078/84648373-3fe6a980-af05-11ea-8919-017387a78d5b.png)

It contains all the information that is needed to make the plot below. It's also the same data that generates the json output on the command line.
