### ISSUE TITLE
Can you please help me with following 2 questions:

### ISSUE THREAD

**Issue by rlrahulkanojia** [vita-epfl/openpifpaf#233]
1) Can the model be trained without caf25 as head. will the model be accurate if trained only using cif and caf?

2) Margin loss is always null during training. Is there any specific reason for keeping it?

**Comment by svenkreiss** [comment]
1. You can train a model without caf25.
2. It's off by default.

**Comment by rlrahulkanojia** [comment]
When should my loss start converging while training?

**Comment by svenkreiss** [comment]
It should go down right from the beginning.

**Comment by rlrahulkanojia** [comment]
The loss of the model I am training hovers around 2 - 3 for starting 60 epochs. Is that how it is supposed to be?
