### ISSUE TITLE
Can we run openpifpaf on iOS ?

### ISSUE THREAD

**Issue by sgu-fai** [vita-epfl/openpifpaf#234]
I was wondering if we can run openpifpaf on iOS ?

**Comment by svenkreiss** [comment]
This recent change might be relevant for you (#240) which will be released in 0.11.7.

**Comment by bonseyes-admin** [comment]
Yes openpifpaf runs on iOS.

**Comment by sgu-fai** [comment]
How it run on iOS?  
The model can be converted to TensorFlow lite ? is it compatible?
