### ISSUE TITLE
FPS performance

### ISSUE THREAD

**Issue by petalatuy** [vita-epfl/openpifpaf#237]
What is the expected frame rate for pifpaf? I'm only getting ~4fps running on a Tesla V100

**Comment by svenkreiss** [comment]
If you only use `--json-output`, this should be a lot faster. When you create an output video, the drawing routines are a big factor and should not be used if you need performance.

**Comment by svenkreiss** [comment]
All our numbers are for `--long-edge=641`. Processing is slower for higher resolutions.

**Comment by petalatuy** [comment]
Hi @svenkreiss , thanks for you fast reply!

I got ~15 fps with --json-output. Just one more question, Can I get as much fps as possible? I don't have to respect the original frame rate of the video, and I would like to use 100% of my gpu power.

**Comment by svenkreiss** [comment]
Are you running `openpifpaf.video`? That uses OpenCV as backend and does not support data pre-fetching so it would be tough to utilize your nice V100 more. The loading from disk and preprocessing is not parallelized in that script. The PyTorch datasets/dataloaders would be more performant but they are only used for training. For training we have really nice utilization of V100 GPUs :)

Any chance you want to process multiple videos? Try running multiple `openpifpaf.video` commands on the same GPU in parallel. While one script is loading more data from disk, the other can use the GPU. That should boost your overall performance.
