### ISSUE TITLE
Issue with ATen during conversion to ONNX

### ISSUE THREAD

**Issue by mdenna-nviso** [vita-epfl/openpifpaf#238]
Hi,
I was trying to convert the latest openpifpaf model 0.11.5 to ONNX but the simplification step fails due to the presence of ATen node.

Seems to be related to this: https://leimao.github.io/blog/PyTorch-ATen-ONNX/

This node was not present in previous versions of the model. This is quite problematic for us, any way it can be avoided?

Thanks
Maurizio

**Comment by svenkreiss** [comment]
I think this node comes from a new version of PyTorch. Which simplification step is that? Something that comes with PyTorch? It can be that a third-party package hasn't updated to the new PyTorch version.

There is a test case for ONNX export and that passes. Can you try whether your ONNX model is useful without the simplification?

**Comment by mdenna-nviso** [comment]
We installed openpifpaf v. 11.5 and started the export tool from the command line. I will check the pytorch version. I will try to run onnx model unsimplified, but the simplification step is actually needed to be able to convert onnx to lpdnn.

The error we get is this:
Optimizing.. Error, optimization skipped
_Map_base::at
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mdenna/dvl/sdk-build/x86_64-ubuntu16/install/tools/onnxsim/__main__.py", line 38, in <module>
    main()
  File "/home/mdenna/dvl/sdk-build/x86_64-ubuntu16/install/tools/onnxsim/__main__.py", line 31, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, input_shapes=input_shapes)
  File "/home/mdenna/dvl/sdk-build/x86_64-ubuntu16/install/tools/onnxsim/onnx_simplifier.py", line 261, in simplify
    res = forward_all(model_opt, input_shapes=input_shapes)
  File "/home/mdenna/dvl/sdk-build/x86_64-ubuntu16/install/tools/onnxsim/onnx_simplifier.py", line 140, in forward_all
    res = forward(model, input_shapes=input_shapes)
  File "/home/mdenna/dvl/sdk-build/x86_64-ubuntu16/install/tools/onnxsim/onnx_simplifier.py", line 128, in forward
    sess = rt.InferenceSession(model.SerializeToString())
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 23, in _init_
    self._load_model()
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 37, in _load_model
    self._sess.read_bytes(self._path_or_bytes, providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: ATen is not a registered function/op
Simplifying.. 
b'Simplifying...\n'
Error while simplifying ONNX model: /home/mdenna/dvl/sdk/catalog/object-detection/body-pose/models/body-pose-openpifpaf/resnet50/blobs/openpifpaf0.11.5_resnet50.onn

**Comment by svenkreiss** [comment]
This seems related: https://github.com/daquexian/onnx-simplifier/issues/74

**Comment by mdenna-nviso** [comment]
It seems tensorrt is not able to run the full model:
jetson xavier, jetpack 4.3:
./trtexec --avgRuns=10 --onnx=/home/nviso/openpifpaf0.11.5_resnet50.onnx --fp16 --batch=8 --iterations=10000 --output=prob --useDLACore=0 --useSpinWait --allowGPUFallback

Would it be possible to export the backbone network separately from the final part?

**Comment by svenkreiss** [comment]
Yes, export `model.base_net` instead of `model`.

**Comment by svenkreiss** [comment]
The problem seems to be traceable to these lines in heads.py where `+=` should be replaced with `.add_()`:
```
            cif_head[:, :, 1:3].add_(index_field)
        if caf_head is not None:
            caf_head[:, :, 1:3].add_(index_field)
            caf_head[:, :, 3:5].add_(index_field)
```
I will prepare a PR for this.
