### ISSUE TITLE
L1 loss function for a single two-dimensional vector 

### ISSUE THREAD

**Issue by hellojialee** [vita-epfl/openpifpaf#239]
Hi, @svenkreiss 

Could you please tell me why you compute the 2-norm of every single two-dimensional vector and sum them as the L1 loss, rather than directly compute the L1 loss of the inferred tensors, e.g. `torch.abs(pred_tensor - gt_tensor)`?

In math, these two kinds of computation methods (1-norm and 2-norm) have the same effect.

**Comment by hellojialee** [comment]
In my opinion, torch.sqrt((x1 - t1)**2 + (x2 - t2)**2) may bypass the zero point that is not differentiable compared with torch.abs(x1, t1) + torch.abs(x2, t2). So what's the motivation? Thank you.

**Comment by svenkreiss** [comment]
L2 has a different symmetry than L1. L1 creates a bias to axis-aligned distances.

**Comment by hellojialee** [comment]
Thanks for your quick reply! The self-defined l1_loss was not used by default. 

https://github.com/vita-epfl/openpifpaf/blob/6412cea7d879bd9a57761a228cf7211661906469/openpifpaf/network/losses.py#L386

**Comment by svenkreiss** [comment]
Correct.
