### ISSUE TITLE
Export ONNX fixed input size and export of backbone seperate

### ISSUE THREAD

**Issue by bonseyes-admin** [vita-epfl/openpifpaf#241]
Hi,

On certain platforms it is not possible to run the ONNX model "as is" due to version issues and that dynamic tensors are not often supported in older versions of ONNX software.

The work around to these issues are:

a) Set the input size (w,h) used in the export of the ONNX model to a fixed size via a command line option
b) Set option to export all or parts of the network:
1) Entire network
2) Backbone (ShuffleNet/ResNet50) only
3) Heads CIF/CAF only

Thanks.

**Comment by svenkreiss** [comment]
Can you clarify what you mean by “dynamic”? Nothing is dynamic in the export. I thought the problem was that we have two output tensors in a tuple instead of one output tensor, but before we had like 9 output tensors and you made that work.

**Comment by bonseyes-admin** [comment]
Dynamic means that the shape is not known. However this was addressed by using a fixed input size, it was more a comment in general that although ONNX export supports dynamic_axes it is not very well supported.

**Comment by svenkreiss** [comment]
That feature was not enabled in OpenPifPaf.

**Comment by ganler** [comment]
Hi @svenkreiss , great work!

So I wonder if you have any plan or idea to support dynamic shape? I tried some tricks but they didn't work,

I tried the following exporting method and at least the ONNX Simplifier can handle the output file. But when I tried to use TensorRT it is reported that the model is broken. So I wonder is there any other inputs are `shape-variable` inside the model? Cuz typically we can make a CV model to own dynamic shape functionality by telling torch the input and output dimensions are dynamic.

```python
    torch.onnx.export(
        model, dummy_input, outfile, verbose=verbose,
        input_names=input_names, output_names=output_names,
        # keep_initializers_as_inputs=True,
        opset_version=11,
        # do_constant_folding=True,
        dynamic_axes = {"input": [0, 2, 3], "cif": [0, 3, 4], "caf": [0, 3, 4]}
    )
```

The model I was practicing is the ResNet50 model. Thanks for your help in advance.

**Comment by svenkreiss** [comment]
Hi @ganler . Thanks for your interest. I think I remember some hard-coded "int" conversions that I am sure wouldn't work with `dynamic_axes`. The original reason for this might be outdated now. Do you mind opening a separate issue for this so we can communicate and test together?
