### ISSUE TITLE
Confusions on COCO_UPRIGHT_POSE and COCO_DAVINCI_POSE

### ISSUE THREAD

**Issue by tfzhou** [vita-epfl/openpifpaf#253]
Hi @svenkreiss Thanks for the great project!

I am confused about the two constants COCO_UPRIGHT_POSE and COCO_DAVINCI_POSE. How the values are computed? How should I compute the values for other datasets, which may have different keypoints from coco?

**Comment by svenkreiss** [comment]
The davinci pose isn't used anywhere. You can ignore that. 

The upright pose is only used to aid a bit the inference of joint sizes from bounding boxes. You should be able to use any common pose from your dataset.

**Comment by tfzhou** [comment]
Thanks. I have got my values for the upright pose. Will back to you if I met extra problems.
