### ISSUE TITLE
Build from source and evaluation on COCO

### ISSUE THREAD

**Issue by annopackage** [vita-epfl/openpifpaf#254]
Hi, thanks for your wonderful work.
I want to know how to build the code from source. After cloning your rep in v0.10.0, and run python openpifpaf.eval_coco, some issues occurs: "No module named 'openpifpaf.functional''

Could you tell me how to solve this issue?

**Comment by svenkreiss** [comment]
Please either follow the install instructions: https://vita-epfl.github.io/openpifpaf/intro.html#install
Or the development instructions if you want to modify OpenPifPaf code: https://vita-epfl.github.io/openpifpaf/dev.html#modify-code

**Comment by annopackage** [comment]
Thanks for your reply, I will carefully read the instructions. In addition, the version 0.8.0 doesn't meet aforementioned issue.
