### ISSUE TITLE
The question about Part Intensity Fields

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#258]
Hi!
I have a question about your paper
I don't understand "The confidence map of a PIF is very coarse" in Part 3.2 Part Intensity Fields
what is "coarse"?
<img width="584" alt="Screen Shot 2020-08-10 at 12 19 00" src="https://user-images.githubusercontent.com/43095377/89753758-ae11ac00-db03-11ea-92df-a078e99ec7da.png">

Thank you

**Comment by svenkreiss** [comment]
Feature map cells can be large (up to 32x32 pixels). There is only one value per cell.
