### ISSUE TITLE
Could PixelShuffle be changed to ConvTranspose2d?

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [vita-epfl/openpifpaf#259]
For same performance, could PixelShuffle be changed to  ConvTranspose2d during training?
@svenkreiss   And could you share your training log?

**Comment by svenkreiss** [comment]
There is no particular reason for PixelShuffle. Feel free to try something else.

Usually I share my training logs here: https://github.com/vita-epfl/openpifpaf-torchhub/releases
But for the last shufflenet models I must have forgotten. I will make sure to remember to share the next ones.

**Comment by MoonBunnyZZZ** [comment]
> There is no particular reason for PixelShuffle. Feel free to try something else.
> 
> Usually I share my training logs here: https://github.com/vita-epfl/openpifpaf-torchhub/releases
> But for the last shufflenet models I must have forgotten. I will make sure to remember to share the next ones.

Thank you
