### ISSUE TITLE
The theoretical upper bound of the system

### ISSUE THREAD

**Issue by hellojialee** [vita-epfl/openpifpaf#260]
Can anyone provide the mAP metrics obtained by running the encoder and decoder directly?
I'm interested in this question. I notice a big drop in AP due to the human skeleton configuration. Thanks!

**Comment by svenkreiss** [comment]
Hello @hellojialee , just wanted to say that this is a good question and I was hoping to get you a more precise answer quicker. I still don't have any precise numbers right now. I did test this quite a while ago. You are right that a fairly sparse skeleton has a constrained upper bound. But I do remember that the option to add denser connections helped a lot. I am planning to have a feature in the next version (hopefully) that allows to run evaluation on ground truth fields and that should produce the number you are after.
