### ISSUE TITLE
Occluded points

### ISSUE THREAD

**Issue by gondimjoaom** [vita-epfl/openpifpaf#261]
Hi! Thank you for this amazing tool!

I'm currently using openpifpaf to train my own custom pose estimator model. I'm now annotating some images and came across a question.

Does occluded points help the model training or they are bad for learning? Depending on the position of the person on camera, his left hip is occluded, I do know where to add the point, but it is not seen.

I have the option of downloading annotations where occluded points are marked, should I use it?

**Comment by petalatuy** [comment]
I have the same question too!
Does PIFPAF use occluded keypoints annotation for training?
For training with my own dataset should I annotate occluded keypoints also?

**Comment by svenkreiss** [comment]
When training on COCO, the occluded keypoints are included by default.

**Comment by gondimjoaom** [comment]
Got it! Thanks @svenkreiss :)
