### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by BigTianyc** [vita-epfl/openpifpaf#265]
I have 8 GPUs with 16GB memory for each one. However, errors happen when the batch size is set larger than 2. Is it normal? What about your  GPU？Details of error message is shown below:
RuntimeError: CUDA out of memory. Tried to allocate 468.00 MiB (GPU 0; 15.90 GiB total capacity; 13.42 GiB already allocated; 85.88 MiB free; 1.67 GiB cached)

**Comment by svenkreiss** [comment]
No, that is not normal.

Are you using the training command as given in the Guide?

**Comment by gondimjoaom** [comment]
Maybe your GPUs are being used by someone else, or, if you are using docker your shared memory is too low. --shm-size might solve it
