### ISSUE TITLE
add Laplace loss make training fail

### ISSUE THREAD

**Issue by realJiaLi** [vita-epfl/openpifpaf#269]
Hi, thank you again for your great work!  I follow your method of applying the Laplace loss to supervise the vector regression in my project. 

But each time, I met the Nan problem after the first backward step. If I change the Laplace loss with normal L1 loss, everything will be fine. I add additional conv layers just as you to infer the spread_b (logb) of the vectors if Laplace loss is used. Also, I add ReLu after the spread_b regression to ensure the logb > 0.
Did I miss something? Or can you give me some help? 

Thank you!

**Comment by svenkreiss** [comment]
You are not using openpifpaf, right?
You have written yourself a loss for another project?

**Comment by realJiaLi** [comment]
Yes, but I followed your practice totally. The ground truth vectors are about in the range of (-200, 200). Most of them are within (-50, 50). Could you give me some hints?

**Comment by svenkreiss** [comment]
I have no idea what the problem might be.
