### ISSUE TITLE
The formula in part greedy coding

### ISSUE THREAD

**Issue by thanhtrung98** [vita-epfl/openpifpaf#275]
Hi!
I don't understand the formula in Greedy coding.
Can You explain the element in the formula?
<img width="457" alt="Screen Shot 2020-08-29 at 19 39 54" src="https://user-images.githubusercontent.com/43095377/91637099-06b3d500-ea30-11ea-85db-0ab277516f58.png">

**Comment by svenkreiss** [comment]
Which element?

I would like to help you, but you need to have precise questions. If the paper is overall not clear to you, we will have longer follow up work in the future that might clarify things.
