### ISSUE TITLE
How to train pifpaf using ResNet:

### ISSUE THREAD

**Issue by gondimjoaom** [vita-epfl/openpifpaf#280]
I currently running `time CUDA_VISIBLE_DEVICES=0,1,2 python3 -m openpifpaf.train --lr=0.0001 --momentum=0.98 --b-scale=10.0   --epochs=350   --lr-decay 130 140   --lr-decay-epochs=10   --batch-size=32   --square-edge=385   --weight-decay=1e-5   --update-batchnorm-runningstatistics   --basenet=resnet50   --headnets cif caf caf25`

buy the weights created seems to get worse. The resnet50-200527-171310-cif-caf-caf25-o10s-c0b7ae80.pkl was able to detect some of the keypoints in my custom dataset, but this new one doesn't find any.

What am I doing wrong here?

One of my colleagues created a scrip that save an image with a train/val loss graphic, if that helps.
![image (11)](https://user-images.githubusercontent.com/29072586/93527943-ff396a80-f90f-11ea-8732-0251a5a6f2ae.png)

We're thinking on creating a pull request with the scrip to create such graphic (really simple) from the .log file. Would that be useful?

**Comment by svenkreiss** [comment]
You can visualize log files (including the plot above) with `python -m openpifpaf.logs nameofyourlogfile`.

**Comment by gondimjoaom** [comment]
Ops, didn't see that. I'm sorry.

But is there something wrong with the way I'm training resnet50?

**Comment by svenkreiss** [comment]
Losses depend on the dataset. It is normal that the loss is huge for the first few batches. That is why there is the learning rate warmup. Later in the training, your loss seems noisy and the learning rate decay does not seem to affect that. 

For a reference, this is the log file for the pretrained resnet50 model in dev: https://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.12a1/resnet50-200912-124649-cocokp-o10s.pkl.log
You can download it and visualize it with the previous command.
I am using releases in this separate repository to share pretrained models and their log files: https://github.com/vita-epfl/openpifpaf-torchhub

Also, investigate your training data. Run the train command with `--debug-images --debug-indices cif:5 caf:5` to produce debug plots for the cif and caf ground truth fields that are used for training.

I will extend the Guide and with this information as well.

**Comment by gondimjoaom** [comment]
I appreciate a lot your help with this :)
I'll work on this today!

**Comment by gondimjoaom** [comment]
PS: the command you mentioned outputs a log file? If so, where? If it shows an image, I'm not being able to see as I'm working with docker inside a ssh server

**Comment by svenkreiss** [comment]
You can run this on your laptop without a GPU. When debug is enabled, the training dataset is not randomized and therefore you only need the first few images in your dataset locally. You need to be able to see matplotlib outputs. I use [itermplot](https://github.com/daleroberts/itermplot).

I am curious about the setup: Is there a way how you normally debug plots remotely? Do you always create image files on your remote machine? Or you use jupyter notebooks? ... I am happy to improve the interface if it is not too complicated to do.

**Comment by gondimjoaom** [comment]
Got it.

Depends on what I have to do. I normally create the image an open it with vscode remote. Jupyter is also an option, but there are a feel other steps when using docker inside the remote machine. Using VNC clients is also another option. At the moment, I tried to tunnel the X server with ssh -X since docker was not needed with your suggestion, but I ran into this warning:

`/home.nfs/joao.gondim/openpifpaf/openpifpaf/show/canvas.py:38: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.`

**Comment by gondimjoaom** [comment]
The warning did not appear running on my laptop.

**Comment by svenkreiss** [comment]
If you know of a backend that is working on your server, you can switch to it by prepending your training command: `MPLBACKEND=agg python3 -m openpifpaf.train ...`. This would set the backend to `agg` but you can use something else. This works for all Python scripts that use matplotlib.

**Comment by gondimjoaom** [comment]
I tried to run the command to see logs of https://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.12a1/resnet50-200912-124649-cocokp-o10s.pkl.log but i ran into ad KeyError:

`python3 -m openpifpaf.logs resnet50-200527-171310-cif-caf-caf25-o10s.pkl.log .
No handles with labels found to put in legend.
No handles with labels found to put in legend.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jmg/.local/lib/python3.8/site-packages/openpifpaf/logs.py", line 567, in <module>
    main()
  File "/home/jmg/.local/lib/python3.8/site-packages/openpifpaf/logs.py", line 562, in main
    Plots(args.log_file, args.label, args.output, first_epoch=args.first_epoch).show_all(
  File "/home/jmg/.local/lib/python3.8/site-packages/openpifpaf/logs.py", line 327, in show_all
    pprint(self.process_arguments())
  File "/home/jmg/.local/lib/python3.8/site-packages/openpifpaf/logs.py", line 95, in process_arguments
    return {label: data['process'][0]['argv'][1:]
  File "/home/jmg/.local/lib/python3.8/site-packages/openpifpaf/logs.py", line 95, in <dictcomp>
    return {label: data['process'][0]['argv'][1:]
KeyError: 'process'`

**Comment by svenkreiss** [comment]
I just tried it and it works. Is there an extra dot `.` in your command?
I ran this: `python -m openpifpaf.logs resnet50-200912-124649-cocokp-o10s.pkl.log --no-share-y`. 
Without the `--no-share-y` option, the scaling seems a bit weird. I should fix that.

**Comment by gondimjoaom** [comment]
yes, there was. Didn't see that! I'm sorry

**Comment by svenkreiss** [comment]
No worries. Glad it works now. OpenPifPaf could use some improvements on its error messages.

**Comment by svenkreiss** [comment]
Closing this for now. Feel free to open new issues for new questions.
