### ISSUE TITLE
Somobody tried to install this on Jetson Nano?

### ISSUE THREAD

**Issue by juancaceres** [vita-epfl/openpifpaf#298]
I want to know if jetson nano with jetpack 4.4 R32.4.4 it's supported?

**Comment by thancaocuong** [comment]
@juancaceres I did installed it on jetson nx without any problem. So expected that it will work well on jetson nano with the same jetpack version.

**Comment by tucachmo2202** [comment]
> @juancaceres I did installed it on jetson nx without any problem. So expected that it will work well on jetson nano with the same jetpack version.
hi,
could you tell me the way you install openpifpaf on jetson nx. I try install openpifpaf by using command: "pip3 install openpifpaf" and an other way is clone this repo then "sudo pip3 install -e ." ,but both are wrong.

**Comment by agrija9** [comment]
Hey @thancaocuong, would you mind sharing what pifpaf model did you use to run on the Jetson in realtime?
