### ISSUE TITLE
Training Preparation

### ISSUE THREAD

**Issue by Liuxinyue521** [vita-epfl/openpifpaf#300]
Hi, first of all, your job is very expressive.
When I try to follow pifpaf guide to train a model, I get an error: FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/Shared drives/liushuai.zhaoxinyue/pifpaf/outputs/resnet50-201029-175811-cif-caf-caf25.pkl.log'.
And the gsutil comand in colab (when downloading coco dataset) seems not working, saying: BucketNotFoundException: 404 gs://images.cocodataset.org bucket does not exist.
So I use some other scripts to download the datasets: https://gist.github.com/mkocabas/a6177fc00315403d31572e17700d7fd9
The "NoFileError" occured after I run
!time CUDA_VISIBLE_DEVICES=0,1,2 python3 -m openpifpaf.train --lr=0.0001 --momentum=0.98 --b-scale=10.0 --epochs=350 --lr-decay 130 140 --lr-decay-epochs=10 --batch-size=32 --square-edge=385 --weight-decay=1e-5 --update-batchnorm-runningstatistics --basenet=resnet50 --headnets cif caf caf25
So what do I need to do else to solve this? 
Thanks in advance.

**Comment by svenkreiss** [comment]
Hi @Liuxinyue521 ,

The COCO dataset seems to have moved very recently. It wasn't clear to me whether this is permanent or not. Our instructions are updated in the dev Guide but that is not merged to master yet: https://vita-epfl.github.io/openpifpaf/dev/datasets.html#download-coco-data

Your error indicates more a problem with the output. Can you please make sure you have an "outputs" folder in your current directory?

Please let us know whether that worked and good luck!

**Comment by Liuxinyue521** [comment]
> Hi @Liuxinyue521 ,
> 
> The COCO dataset seems to have moved very recently. It wasn't clear to me whether this is permanent or not. Our instructions are updated in the dev Guide but that is not merged to master yet: https://vita-epfl.github.io/openpifpaf/dev/datasets.html#download-coco-data
> 
> Your error indicates more a problem with the output. Can you please make sure you have an "outputs" folder in your current directory?
> 
> Please let us know whether that worked and good luck!

Thanks a lot! It works after create a 'outputs' folder. But CUDA out of memory error occurs. I noticed that there is other people's work running on both two gpus on my machine. So I'm gonna try it on colab.

**Comment by Liuxinyue521** [comment]
> Hi @Liuxinyue521 ,
> 
> The COCO dataset seems to have moved very recently. It wasn't clear to me whether this is permanent or not. Our instructions are updated in the dev Guide but that is not merged to master yet: https://vita-epfl.github.io/openpifpaf/dev/datasets.html#download-coco-data
> 
> Your error indicates more a problem with the output. Can you please make sure you have an "outputs" folder in your current directory?
> 
> Please let us know whether that worked and good luck!

Hi, I got another problem, if I want to use trained model to predict on my custom images, what should I modify in the prediction API of pifpaf guide? I already tried by replacing the argument chechpoints with your released model in torchhub
(resnet50-200527-171310-cif-caf-caf25-o10s-c0b7ae80.pkl), but I got an error. Below is the original code in the guide page.

**net_cpu, _ = openpifpaf.network.factory(checkpoint='shufflenetv2k16w', download_progress=False)
net = net_cpu.to(device)

openpifpaf.decoder.CifSeeds.threshold = 0.5
openpifpaf.decoder.nms.Keypoints.keypoint_threshold = 0.2
openpifpaf.decoder.nms.Keypoints.instance_threshold = 0.2
processor = openpifpaf.decoder.factory_decode(net.head_nets, basenet_stride=net.base_net.stride**

**Comment by svenkreiss** [comment]
You shouldn't have to modify any code to use a pretrained model. You can just use the name of the model on the command line: `--checkpoint=resnet50`.

What is the error message that you got?

**Comment by Liuxinyue521** [comment]
> You shouldn't have to modify any code to use a pretrained model. You can just use the name of the model on the command line: `--checkpoint=resnet50`.
> 
> What is the error message that you got?

This works. What I mean is I want to use specific trained model to predict on images. As the guide indicate, the checkpoint only have three options, so what should I do if I want to use my own trained pifpaf model to make predictions?

**Comment by svenkreiss** [comment]
You can give the path of your model to the `--checkpoint=<yourmodelpath>` argument.

**Comment by Liuxinyue521** [comment]
> You can give the path of your model to the `--checkpoint=<yourmodelpath>` argument.

Okay, thank you for your quick reply!

**Comment by Liuxinyue521** [comment]
> > You can give the path of your model to the `--checkpoint=<yourmodelpath>` argument.
> 
> Okay, thank you for your quick reply!

Hi, I got another problem: if I want to train on my own datasets, which parts of the codes should I change? And I noticed that you provide three datasets (coco, mpii, nightowls), how to train on specific dataset?

**Comment by svenkreiss** [comment]
Adding a new dataset used to involve quite a bit of coding. In the dev branch, this is all factorized and you can add your own dataset without even modifying core openpifpaf code. You can make your dataset a plugin and then train models and run prediction.

Some documentation is here: https://vita-epfl.github.io/openpifpaf/dev/plugins_overview.html 
... and the following chapter walks through a plugin for Cifar10.
