### ISSUE TITLE
Is there any guildence about adding new dataset for training?

### ISSUE THREAD

**Issue by dreamPoet** [vita-epfl/openpifpaf#306]
I want to train and eval pifpaf on AI challenge dataset. Thx.

**Comment by svenkreiss** [comment]
Unfortunately not in the stable release yet, but for the dev branch:
https://vita-epfl.github.io/openpifpaf/dev/plugins_overview.html

The code in the master branch is quite difficult to extend. In the dev branch, there is a plugin system that allows to add a new dataset without modifying core code. The dev guide also has an example plugin, Cifar10.
