### ISSUE TITLE
Inquiry about the meaning of PAF dimensions

### ISSUE THREAD

**Issue by ganler** [vita-epfl/openpifpaf#309]
Hi, thanks for your great work!

If I understood pifpaf correctly, I think the output PAF tensor dimensions represent `conf, [x1, y1, b1], [x2, y2, b2]` which is of 7 dimensions. However, when I checked your pre-trained model I found that there're 9 dimensions in the output PAF tensor. I'd like to the meanings of the 9 dimensions. 

BTW, I saw that you also have a work-in-progress C++ codebase which is about the decoder. May I know if the codes are already available or they are still under experiments? Thanks for your help in advance.

**Comment by svenkreiss** [comment]
In later versions, there is also a scale prediction similar to what is in PIF. And the order of these 9 entries is different between master and dev. Cleanest insight can probably bet gotten from this line (dev branch):
https://github.com/vita-epfl/openpifpaf/blob/28edef8a6f4ed5f53cf6c08f54a85e96dfb10aee/openpifpaf/network/heads.py#L250
So it is `conf, x1, y1, x2, y2, b1, b2, sigma1, sigma2`.

Help on the C++ codebase would be very much appreciated. I don't know of anyone who is actively porting this to be compatible with `dev`.

**Comment by ganler** [comment]
Thanks for your help! I am trying to make the C++ codes compatible with the pre-trained model so that we may easily handle the outputs of the exported ONNX model.

**Comment by svenkreiss** [comment]
Great, please keep us updated and feel free to ask more questions any time.
