### ISSUE TITLE
Exclude small bounding boxes and fewer keypoints from training

### ISSUE THREAD

**Issue by gondimjoaom** [vita-epfl/openpifpaf#311]
Hi, I'm currently training openpifpaf on a custom dataset. My problem is that when annotations were made, people too far on the image (which will have fewer keypoints or small bounding boxes) were ignored. But, since openpifpaf is very good on detecting even small people, I believe that not passing annotations from existing people on image is interfering with the training.

I'm having good mAP on val dataset, but with a some false positives.

I wonder if there is a way to train openpifpaf excluding found bounding boxes that are too small (therefore not valuable for what I want). Even if it is inside the code and not parameterized. 

Average Precision  (AP) @[ IoU=0.50:0.95 \| area=   all \| maxDets= 20 ] = 0.876
--
Average Precision  (AP) @[ IoU=0.50      \| area=   all \| maxDets= 20 ] = 0.964
Average Precision  (AP) @[ IoU=0.75      \| area=   all \| maxDets= 20 ] = 0.933
Average Precision  (AP) @[ IoU=0.50:0.95 \| area=medium \| maxDets= 20 ] = 0.439
Average Precision  (AP) @[ IoU=0.50:0.95 \| area= large \| maxDets= 20 ] = 0.886
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=   all \| maxDets= 20 ] = 0.913
Average Recall     (AR) @[ IoU=0.50      \| area=   all \| maxDets= 20 ] = 0.987
Average Recall     (AR) @[ IoU=0.75      \| area=   all \| maxDets= 20 ] = 0.958
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=medium \| maxDets= 20 ] = 0.790
Average Recall     (AR) @[ IoU=0.50:0.95 \| area= large \| maxDets= 20 ] = 0.918

**Comment by petalatuy** [comment]
I have the same problem.

**Comment by svenkreiss** [comment]
Actually, bounding boxes without keypoint annotations are treated as crowd regions: no loss is applied in that area. Also in COCO, there are many bounding boxes (particularly small ones) that don't have keypoint annotations. 

In the debug plots for confidences, crowd regions appear as "holes" in the color map.

Is that not working for you? Do you have an example that I can test?

**Comment by gondimjoaom** [comment]
I didn't explain properly. Here are two images that might help.

![1](https://user-images.githubusercontent.com/29072586/99400915-533bdd80-28c6-11eb-930e-2870a5293cec.png)

Image 1 shows some people detected. The red arrow points to a person that I'm not interested in and **therefore not annotating**, the green arrows point to people I'm interested in, and annotating to create the dataset.

![2](https://user-images.githubusercontent.com/29072586/99400935-58009180-28c6-11eb-9e78-d8fb564b63fb.png)

Image 2 shows what I think my problem is. Since I'm not passing annotations from the far away person, the loss is passed when openpifpaf detects them and the annotation is not present. I think this is leading to some fewer keypoints being detected overlapping existing keypoints that are part of a whole person detected, as shown inside the circle with the red arrow.

I believe that maybe the losses from detected small people that are not annotated in both train and val dataset is making my model detect these fewer overlapping keypoints.

Because these fewer overlapping keypoints are right positioned, I believe mAP still looks good, is that correct?

**Comment by svenkreiss** [comment]
You need to add crowd annotations for people that you don't annotate with keypoints, i.e. you need a crowd annotation over your top left part of the image.

**Comment by gondimjoaom** [comment]
got it. Currently I'm not passing any annotation at all
