### ISSUE TITLE
C++ postprocess for model_0_11

### ISSUE THREAD

**Issue by Larry225** [vita-epfl/openpifpaf#312]
What's the difference between model_0_11 and model_0_8? 
How to get model_0_8's outputs in python interface? 
How to transform model_0_11's outputs to model_0_8's outputs which can be used in C++ interface?  Thx.

**Comment by ganler** [comment]
@Larry225  The model_0_11 seems to be unimplemented if you look at the source codes. The 0_8 version can work. That said, we may need some transformations to leverage 0_8....

**Comment by Larry225** [comment]
@ganler Thanks, the 0_8 version is ok.

**Comment by SidneyRey** [comment]
@ganler How to get model_0_8's outputs in python interface? 
I replace sample_data_0_8's data like this:
pif_c = pif[:, 0, :, :].reshape((-1))
pif_r = pif[:, 1:3, :, :].reshape((-1))
pif_b = pif[:, 3, :, :].reshape((-1))
pif_s = pif[:, 4, :, :].reshape((-1))
paf_c = paf[:, 0, :, :].reshape((-1))
paf_r1 = paf[:, 1:3, :, :].reshape((-1))
paf_r2 = paf[:, 3:5, :, :].reshape((-1))
paf_b1 = paf[:, 7, :, :].reshape((-1))
paf_b2 = paf[:, 8, :, :].reshape((-1))
and then, I use the width and height of my pif feature map.
but, I get the error results.

the pif and paf feature maps were got from python function Generator.fields_batch()。

**Comment by ganler** [comment]
@SidneyRey  I didn't look at the python codes. What I did in my experiments is to (1) convert the model into ONNX and use ONNXRuntime for inference; then I try to convert the outputs{pif, paf} into formats that compatible with the C++ codes; However, it seems that the C++ codes are not so correct to display things as what the python API can do...

**Comment by SidneyRey** [comment]
@ganler thank you for your reply!
