### ISSUE TITLE
dev-branch development

### ISSUE THREAD

**Issue by nguyenbaviet** [vita-epfl/openpifpaf#316]
Hi Svenkreiss,
I am very interested in your project and I love to apply this into my projects at school. As I can see, there are currently some developments on dev branch. I'm really curious about what you plan to do next. It's would be amazing if you can share it with me
Thanks a lot

**Comment by svenkreiss** [comment]
Hi @nguyenbaviet , great to hear you like OpenPifPaf. I have put together a list of things to contribute here: https://vita-epfl.github.io/openpifpaf/dev/dev.html#things-to-contribute 
Maybe something catches your interest.

**Comment by nguyenbaviet** [comment]
Thanks for your reply!
