### ISSUE TITLE
Padding in preprocessing procedure of training

### ISSUE THREAD

**Issue by ChongMingWei** [vita-epfl/openpifpaf#323]
Hello, I trace the training code and find that :
For each image, we will find the max(H,W) and then assign  H or W (the larger one) value 'square_edge'.
Then, we will do padding for the transformed image to make it a square.

But why don't you directly use the transformed image without padding?

Thanks for your reply beforehand!!

**Comment by svenkreiss** [comment]
Hello @ChongMingWei , to make a batch, every image must be of exactly the same size.

**Comment by ChongMingWei** [comment]
@svenkreiss Oops, it seems to be a simple concept.
Thanks a lot!
