### ISSUE TITLE
When I train，i always encounter the following problems“FileNotFoundError: [Errno 2] No such file or directory: 'data-mscoco/images/train2017/000000124562.jpg'”

### ISSUE THREAD

**Issue by happydog555** [vita-epfl/openpifpaf#326]
![无标题](https://user-images.githubusercontent.com/37396129/102465526-b6b55880-4088-11eb-8398-8f616435aa02.png)

i have this picture

**Comment by svenkreiss** [comment]
Please follow these instructions to install the dataset: https://vita-epfl.github.io/openpifpaf/dev/datasets.html#download-coco-data
