### ISSUE TITLE
Extracting only KeyPoints as an OpenCV compatible array

### ISSUE THREAD

**Issue by AksharSharma** [vita-epfl/openpifpaf#328]
Hi!
First of all kudos for building such a great solution. I wanted to know if it is possible to extract just keypoints of the skeletal joints in the image supplied. If yes, can these keypoints be extracted as an open CV compatible array, so that they can serve as a location in image? A way to implement the above will be much appreciated. 
Thanks!

**Comment by vladimirmujagic** [comment]
By calling `python3 -m openpifpaf.predict /path/to/image.jpg --json-output /path/to/predictions.json ` you can get "skeletal joints" data from `keypoints key` in produced json.

Keypoints - 17 of them are stored as flattened array, each 3 consequitve values represent (x, y, conf), you can render using opencv api with that info

**Comment by AksharSharma** [comment]
Thanks for your reply!
Can this also be implemented using the preidct_api? So that I can implement it as part of a script.

**Comment by svenkreiss** [comment]
Hello @AksharSharma , I have just extended the prediction API tutorial to make that final step to get the data out more explicit: https://vita-epfl.github.io/openpifpaf/dev/predict_api.html#prediction

**Comment by AksharSharma** [comment]
Thank you so much @svenkreiss ! That really helped me a lot. Thanks once again to you and @vladimirmujagic  for solving the issue!
