### ISSUE TITLE
Functional.c

### ISSUE THREAD

**Issue by Ivamcoder** [vita-epfl/openpifpaf#33]
Hi @svenkreiss , 
Thanks for your nice paper,
What is the goal of `functional.c` and for what reason it is going to be used?
why it is not written in pyhton?

**Comment by svenkreiss** [comment]
Hi @Ivamcoder, its generated from `functional.pyx` which is Cython. There are some operations in for loops that would create a lot of temporary Python objects in pure Python so I ported that code to Cython. I try to customize as little as possible for performance but those functions made a difference.
