### ISSUE TITLE
Unable to install openpifpaf in linux environment running miniconda

### ISSUE THREAD

**Issue by AksharSharma** [vita-epfl/openpifpaf#330]
Hi!

My installation stops with error: Command "gcc" failed with exit status 1. 
I'm running Ubuntu with miniconda. Following is the full log:-

<-------------------------------------------Log begins here------------------------------------->
Collecting openpifpaf
  Using cached openpifpaf-0.11.9.tar.gz (223 kB)
Requirement already satisfied: pysparkling in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from openpifpaf) (0.6.0)
Requirement already satisfied: python-json-logger in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from openpifpaf) (2.0.1)
Requirement already satisfied: scipy in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from openpifpaf) (1.6.0)
Requirement already satisfied: torch>=1.3.1 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from openpifpaf) (1.7.1)
Requirement already satisfied: torchvision>=0.4 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from openpifpaf) (0.8.2)
Requirement already satisfied: typing-extensions in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from torch>=1.3.1->openpifpaf) (3.7.4.3)
Requirement already satisfied: future>=0.15 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from pysparkling->openpifpaf) (0.18.2)
Requirement already satisfied: boto>=2.36.0 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from pysparkling->openpifpaf) (2.49.0)
Requirement already satisfied: requests>=2.6.0 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from pysparkling->openpifpaf) (2.25.1)
Requirement already satisfied: idna<3,>=2.5 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from requests>=2.6.0->pysparkling->openpifpaf) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from requests>=2.6.0->pysparkling->openpifpaf) (1.26.2)
Requirement already satisfied: chardet<5,>=3.0.2 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from requests>=2.6.0->pysparkling->openpifpaf) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/envs/latest_lib/lib/python3.8/site-packages (from requests>=2.6.0->pysparkling->openpifpaf) (2020.12.5)
Building wheels for collected packages: openpifpaf
  Building wheel for openpifpaf (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/miniconda3/envs/latest_lib/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mnvwf4sq
       cwd: /tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/
  Complete output (103 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/train.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/optimize.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/eval_coco.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/annotation.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/export_onnx.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/count_ops.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/benchmark.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/migrate.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/utils.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/video.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/predict.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/train_instance_scorer.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/logs.py -> build/lib.linux-x86_64-3.8/openpifpaf
  copying openpifpaf/_version.py -> build/lib.linux-x86_64-3.8/openpifpaf
  creating build/lib.linux-x86_64-3.8/openpifpaf/datasets
  copying openpifpaf/datasets/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
  copying openpifpaf/datasets/headmeta.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
  copying openpifpaf/datasets/coco.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
  copying openpifpaf/datasets/image_list.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
  copying openpifpaf/datasets/constants.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
  copying openpifpaf/datasets/collate.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
  copying openpifpaf/datasets/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
  creating build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/profiler_autograd.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/occupancy.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/instance_scorer.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/caf_scored.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/cif_hr.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/utils.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/cif_seeds.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/field_config.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/profiler.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/caf_seeds.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/nms.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  copying openpifpaf/decoder/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
  creating build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
  copying openpifpaf/decoder/generator/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
  copying openpifpaf/decoder/generator/cifcaf.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
  copying openpifpaf/decoder/generator/generator.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
  copying openpifpaf/decoder/generator/cifdet.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
  creating build/lib.linux-x86_64-3.8/openpifpaf/encoder
  copying openpifpaf/encoder/caf.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
  copying openpifpaf/encoder/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
  copying openpifpaf/encoder/annrescaler.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
  copying openpifpaf/encoder/cif.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
  copying openpifpaf/encoder/cifdet.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
  copying openpifpaf/encoder/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
  creating build/lib.linux-x86_64-3.8/openpifpaf/network
  copying openpifpaf/network/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
  copying openpifpaf/network/nets.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
  copying openpifpaf/network/basenetworks.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
  copying openpifpaf/network/trainer.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
  copying openpifpaf/network/heads.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
  copying openpifpaf/network/losses.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
  copying openpifpaf/network/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
  creating build/lib.linux-x86_64-3.8/openpifpaf/show
  copying openpifpaf/show/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
  copying openpifpaf/show/painters.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
  copying openpifpaf/show/canvas.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
  copying openpifpaf/show/cli.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
  copying openpifpaf/show/animation_frame.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
  copying openpifpaf/show/fields.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
  creating build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/unclipped.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/preprocess.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/hflip.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/minsize.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/rotate.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/utils.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/scale.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/compose.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/random.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/pad.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/multi_scale.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/annotations.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/image.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  copying openpifpaf/transforms/crop.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
  creating build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/caf.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/occupancy.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/cifhr.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/cif.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/cli.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/cifdet.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/seeds.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  copying openpifpaf/visualizer/base.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
  running build_ext
  building 'openpifpaf.functional' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/openpifpaf
  gcc -pthread -B /home/ubuntu/miniconda3/envs/latest_lib/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/miniconda3/envs/latest_lib/lib/python3.8/site-packages/numpy/core/include -I/home/ubuntu/miniconda3/envs/latest_lib/include/python3.8 -c openpifpaf/functional.c -o build/temp.linux-x86_64-3.8/openpifpaf/functional.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for openpifpaf
  Running setup.py clean for openpifpaf
Failed to build openpifpaf
Installing collected packages: openpifpaf, matplotlib
    Running setup.py install for openpifpaf ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/miniconda3/envs/latest_lib/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vacrbrog/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/miniconda3/envs/latest_lib/include/python3.8/openpifpaf
         cwd: /tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/
    Complete output (103 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/train.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/optimize.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/eval_coco.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/annotation.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/export_onnx.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/count_ops.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/benchmark.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/migrate.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/utils.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/video.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/predict.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/train_instance_scorer.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/logs.py -> build/lib.linux-x86_64-3.8/openpifpaf
    copying openpifpaf/_version.py -> build/lib.linux-x86_64-3.8/openpifpaf
    creating build/lib.linux-x86_64-3.8/openpifpaf/datasets
    copying openpifpaf/datasets/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
    copying openpifpaf/datasets/headmeta.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
    copying openpifpaf/datasets/coco.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
    copying openpifpaf/datasets/image_list.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
    copying openpifpaf/datasets/constants.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
    copying openpifpaf/datasets/collate.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
    copying openpifpaf/datasets/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/datasets
    creating build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/profiler_autograd.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/occupancy.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/instance_scorer.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/caf_scored.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/cif_hr.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/utils.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/cif_seeds.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/field_config.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/profiler.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/caf_seeds.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/nms.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    copying openpifpaf/decoder/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder
    creating build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
    copying openpifpaf/decoder/generator/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
    copying openpifpaf/decoder/generator/cifcaf.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
    copying openpifpaf/decoder/generator/generator.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
    copying openpifpaf/decoder/generator/cifdet.py -> build/lib.linux-x86_64-3.8/openpifpaf/decoder/generator
    creating build/lib.linux-x86_64-3.8/openpifpaf/encoder
    copying openpifpaf/encoder/caf.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
    copying openpifpaf/encoder/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
    copying openpifpaf/encoder/annrescaler.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
    copying openpifpaf/encoder/cif.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
    copying openpifpaf/encoder/cifdet.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
    copying openpifpaf/encoder/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/encoder
    creating build/lib.linux-x86_64-3.8/openpifpaf/network
    copying openpifpaf/network/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
    copying openpifpaf/network/nets.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
    copying openpifpaf/network/basenetworks.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
    copying openpifpaf/network/trainer.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
    copying openpifpaf/network/heads.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
    copying openpifpaf/network/losses.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
    copying openpifpaf/network/factory.py -> build/lib.linux-x86_64-3.8/openpifpaf/network
    creating build/lib.linux-x86_64-3.8/openpifpaf/show
    copying openpifpaf/show/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
    copying openpifpaf/show/painters.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
    copying openpifpaf/show/canvas.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
    copying openpifpaf/show/cli.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
    copying openpifpaf/show/animation_frame.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
    copying openpifpaf/show/fields.py -> build/lib.linux-x86_64-3.8/openpifpaf/show
    creating build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/unclipped.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/preprocess.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/hflip.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/minsize.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/rotate.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/utils.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/scale.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/compose.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/random.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/pad.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/multi_scale.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/annotations.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/image.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    copying openpifpaf/transforms/crop.py -> build/lib.linux-x86_64-3.8/openpifpaf/transforms
    creating build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/caf.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/__init__.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/occupancy.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/cifhr.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/cif.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/cli.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/cifdet.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/seeds.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    copying openpifpaf/visualizer/base.py -> build/lib.linux-x86_64-3.8/openpifpaf/visualizer
    running build_ext
    building 'openpifpaf.functional' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/openpifpaf
    gcc -pthread -B /home/ubuntu/miniconda3/envs/latest_lib/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/miniconda3/envs/latest_lib/lib/python3.8/site-packages/numpy/core/include -I/home/ubuntu/miniconda3/envs/latest_lib/include/python3.8 -c openpifpaf/functional.c -o build/temp.linux-x86_64-3.8/openpifpaf/functional.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/miniconda3/envs/latest_lib/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fd_6z44r/openpifpaf_263d8759903141d0ae231467b5a89f53/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vacrbrog/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/miniconda3/envs/latest_lib/include/python3.8/openpifpaf Check the logs for full command output.

<-------------------------------------------Log ends here------------------------------------->

**Comment by svenkreiss** [comment]
If you build from source, you need gcc. With the beta of version 0.12, most platforms have binary builds now: https://pypi.org/project/openpifpaf/0.12b1/#files
The binary wheel should be used whenever possible and then you don't need a compiler.

**Comment by AksharSharma** [comment]
Thanks @svenkreiss !
That worked
