### ISSUE TITLE
resnet50 v12 keypoints

### ISSUE THREAD

**Issue by vladimirmujagic** [vita-epfl/openpifpaf#336]
Hi,

I am testing newly released models: https://github.com/vita-epfl/openpifpaf-torchhub/releases/tag/v0.12a7

I noticed that number of keypoints and ordering changed, now there is only one keypoint for head instead of eyes, nose, ears.

Is it possible to use old keypoint with new model ?

**Comment by svenkreiss** [comment]
The keypoint config depends on the dataset. The `cocokp` models have all the same keypoints. If you picked the `crowdpose` model then those keypoints are indeed different.

I just ran this command on the dev branch: `python3 -m openpifpaf.predict docs/coco/000000081988.jpg --checkpoint resnet50 --show --long-edge=641` which used model `http://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.12a7/resnet50-201123-175351-cocokp-o10s-127f7fdf.pkl`
to get:
![iTerm2 H70r0o plot](https://user-images.githubusercontent.com/2775078/105498011-ea0a8900-5cbf-11eb-987d-3709b9e5b28c.png)
