### ISSUE TITLE
Problem with cuda and Torch

### ISSUE THREAD

**Issue by rcintas** [vita-epfl/openpifpaf#35]
Hello, I have this error when setting device = torch.device(type="cuda"). With the cpu option it runs ok but at 3fps with 0.5 scale.

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

Setting: Ubuntu 18.04, Nvidia 1080 Ti Cuda 9.1 and cuDNN 7

Thanks!

**Comment by svenkreiss** [comment]
Hello @rcintas. Thanks for trying it out. Is this with your custom code or with the provided `predict.py`?

Make sure you apply `.device()` to the input tensors and to the model itself.

**Comment by rcintas** [comment]
Thanks for your comments, 
Finally it was my mistake I was not updating model to cuda
