### ISSUE TITLE
how detect the start and end of fall process

### ISSUE THREAD

**Issue by MichaelWU0726** [vita-epfl/openpifpaf#359]
Only a frame of the fall process is detected in this project. I want to detect the start and end of falls, so i should how to modify these codes ?

**Comment by svenkreiss** [comment]
hi @MichaelWU0726 , thanks for your interest in openpifpaf. Can you provide more details or context? I don't follow what this is about. Is this maybe related to another project?

**Comment by MichaelWU0726** [comment]
> hi @MichaelWU0726 , thanks for your interest in openpifpaf. Can you provide more details or context? I don't follow what this is about. Is this maybe related to another project?

In order to detect the fall of persons, I tried a project from the following repository that forked from your ones:
`https://github.com/cwlroda/falldetection_openpifpaf`
After running, it only detected and saved one frame picture from every fall. But i want to get the start frame and end frame of every fall action. Hope to get your help sincerely.

**Comment by svenkreiss** [comment]
This seems to be specific to fall detection then. I am not able to help with that here.
