### ISSUE TITLE
Ablation study of dense skeleton?

### ISSUE THREAD

**Issue by jialee93** [vita-epfl/openpifpaf#36]
Hi, could you help me know the contribution of dense connected skeleton VS KINEMATIC_TREE_SKELETON as well as COCO_PERSON_SKELETON?

**Comment by svenkreiss** [comment]
Sorry, we do not have numbers with the latest version.

**Comment by USTClj** [comment]
@svenkreiss Thank you for your reply. Could you give some hint on that? Only a rough number is ok.

**Comment by Will-Hui** [comment]
compare to COCO_PERSON_SKELETON and  KINEMATIC_TREE_SKELETON, do you think the more denser skeleton can improve MAP? Maybe this is important pointview.
