### ISSUE TITLE
Pre processing time  in inference

### ISSUE THREAD

**Issue by NgTuong** [vita-epfl/openpifpaf#360]
Hi, this repo has long_edge args(long edge for input image).
When I use it in inference, it get more time for pre processing.
I find a reason: 
You use PIL library for resizing image although you set condittion for it is Fast=True [here](https://github.com/vita-epfl/openpifpaf/blob/main/openpifpaf/transforms/scale.py#L29)
The resized PIL image get more time than Opencv. I removed it in [here](https://github.com/vita-epfl/openpifpaf/blob/main/openpifpaf/transforms/scale.py#L29) and add scaled resize using opencv before converting to PIL.
Result: speed 0.03 -> 0.003s/frame for pre processing

**Comment by svenkreiss** [comment]
Oh nice. Thanks for sharing that observation @NgTuong .
Just to confirm, this is when you use the `openpifpaf.video` tool?

**Comment by NgTuong** [comment]
Hi @svenkreiss 
Yes, i tested with `openpifpaf.video ` . In `video.py`, I add in [here](https://github.com/vita-epfl/openpifpaf/blob/main/openpifpaf/video.py#L221). 
`
scale_factor = args.long_edge / max(image.shape[:2])
image = cv2.resize(image, None, fx=scale_factor, fy=scale_factor)
`
and removed resized image in [here](https://github.com/vita-epfl/openpifpaf/blob/main/openpifpaf/transforms/scale.py#L15)
It's my change, You have what ideal?

**Comment by svenkreiss** [comment]
Thanks, @NgTuong . I have written a test case to replicate your timing results. 
I have added some modifications to the rescale method in the #362 PR. Once that is in, it would be great if you can confirm that this works for you.

**Comment by NgTuong** [comment]
Thanks @svenkreiss .
This solution is faster (2 time on RTX2080Ti). But t checked in [scale function](https://github.com/vita-epfl/openpifpaf/blob/main/openpifpaf/transforms/scale.py#L15), I didn't understand that it takes a lot of time for preprocessing (80% time) when using resized image in `scale function`. 
![Screenshot from 2021-03-04 08-23-55](https://user-images.githubusercontent.com/42471216/109896336-574c0980-7cc3-11eb-9468-922b20ca0f89.png)
My solution is that not use resized image in `scale function`,  I resized image outside.  My implemented code before converting to Pillow in [here](https://github.com/vita-epfl/openpifpaf/blob/main/openpifpaf/video.py#L221)

> scale_factor = args.long_edge / max(w_org, h_org)
if h_org > w_org:
     target_w, target_h = int(w_org * scale_factor), int(args.long_edge)
else:
    target_w, target_h = int(args.long_edge), int(h_org * scale_factor)
    image = cv2.resize(image, (target_w, target_h), interpolation=cv2.INTER_LINEAR)

I tested again and amazing results:
![Screenshot from 2021-03-04 08-42-01](https://user-images.githubusercontent.com/42471216/109897628-94190000-7cc5-11eb-8a9b-61844cbe4ec6.png)

and accuracy results are the same.

**Comment by svenkreiss** [comment]
Excellent. So if I understand correctly, with v0.12.5, you don't need your modification anymore. I consider this issue closed then. Thanks for reporting! And definitely let us know if you discover something else.
