### ISSUE TITLE
Training with own keypoints config

### ISSUE THREAD

**Issue by NgTuong** [vita-epfl/openpifpaf#365]
Hi @svenkreiss ,
I want to train with keypoints configuration e.g 14 keypoints, 15 keypoint, ... 
how do i need to fix in this [file](https://github.com/vita-epfl/openpifpaf/blob/main/openpifpaf/plugins/coco/constants.py)? and  which params need to be considered?

**Comment by svenkreiss** [comment]
COCO is the plugin that has the most configuration options and is therefore quite large.
Maybe take a look at the CrowdPose plugin instead. I wrote a little tutorial page for it as well: https://vita-epfl.github.io/openpifpaf/plugins_crowdpose.html
Everything you need to modify is here: https://github.com/vita-epfl/openpifpaf/tree/main/openpifpaf/plugins/crowdpose

**Comment by NgTuong** [comment]
thanks @svenkreiss

**Comment by svenkreiss** [comment]
Feel free to post more questions. Also, suggestions and/or contributions to the Guide are very welcome to make it easier for others to customize OpenPifPaf. If you come across something that is missing, feel free to open another issue.
