### ISSUE TITLE
Question on Shell 2Stage, shellFork, visualization

### ISSUE THREAD

**Issue by Ivamcoder** [vita-epfl/openpifpaf#37]
Hi @svenkreiss 

What is the different of  `shellFork, Shell2stage, ..` ?
 and what is the setting which gives the best score ?
 and about context of `Re-Id`  which part of code is related to that? I mean the out put of the network is keypoint location but Re-Id should have id  out put or  .., 

and for visualization when I debug  `visualizer , paf19` the figures are same as figures for `pif17`
for figure5 in paper what should I run?

I would appreciate your comment , thank you so much

Thanks,

**Comment by flowtcw** [comment]
@Ivamcoder Hi, I don't understand ShellFork doing in the network. Can you give me some understanding of it? Thanks :)

**Comment by svenkreiss** [comment]
ShellFork and Shell2Stage are not used.
