### ISSUE TITLE
Question about Cif_Hr

### ISSUE THREAD

**Issue by thancaocuong** [vita-epfl/openpifpaf#375]
Hi, I want to form High Resolution heatmap from Cif. So first I generate Cif from encoder. It works fined. But when I reconstruct the cif_hr using decoder.cif_hr, I've met a problem. About [this line](https://github.com/vita-epfl/openpifpaf/blob/86db61be17467fceca323ddfd15088bace75724c/openpifpaf/decoder/utils/cif_hr.py#L32) , x and y are the offset vector coordinates, then you use ```scalar_square_add_gauss_with_max``` to generate the gaussian map. So x, y is not real coordinate of keypoints? How can I get the heatmap?
I'm sure that the cif was generated correctly 

![cif](https://user-images.githubusercontent.com/43930651/112788249-aa2b9d80-9084-11eb-921e-f0113aaadd70.png)

**Comment by svenkreiss** [comment]
The line you are pointing to is part of code that creates a high resolution map that is at the resolution of the input image. The output of the head is in the coordinates of the CIF head that has an effective stride with respect to the image. For our models, usually that stride is eight.

I have written a short description of the coordinate system here: https://vita-epfl.github.io/openpifpaf/models.html#coordinate-system
It is such that you can simply multiply by stride to go from CIF coordinates to image pixel coordinates.

Does that help?

**Comment by thancaocuong** [comment]
@svenkreiss  [this line](https://github.com/vita-epfl/openpifpaf/blob/86db61be17467fceca323ddfd15088bace75724c/openpifpaf/decoder/utils/cif_hr.py#L31) extract the Confidence score, x, y, _, sigma. So that the x and y is the coordinates at the resolution of the input image after multiply with stride?

**Comment by thancaocuong** [comment]
@svenkreiss  oh sorry, I've forgot to add index to regression fields. So I think now there's no problem. Thank for your quick answer.
