### ISSUE TITLE
Ability to get the positions of pose estimation

### ISSUE THREAD

**Issue by d2hf** [vita-epfl/openpifpaf#40]
Hey, I have been searching around on how to get the position in a dict, I couldn't figure it out.
Any tips on how to do it?

**Comment by svenkreiss** [comment]
How about this implementation inside of `predict.py`: https://github.com/vita-epfl/openpifpaf/blob/master/openpifpaf/predict.py#L112
Does this help you?

**Comment by d2hf** [comment]
it does, and it solves my issue! thank you.

**Comment by svenkreiss** [comment]
Great!
