### ISSUE TITLE
Using an ImageNet pretrained ResNet backbone vs training it from scratch

### ISSUE THREAD

**Issue by philferriere** [vita-epfl/openpifpaf#55]
First off, congrats on putting together an outstanding human pose estimator. This is truly impressive work.

In your current implementation, you use a *pre-trained* ResNetv2 as a backbone. One of the first operations your backbone code performs, however, is **removing the pooling layer** at the end of the ResNetv2 input stem, [here](https://github.com/vita-epfl/openpifpaf/blob/23a66b1ce490e4c7cd36330701da411af1bbedf0/openpifpaf/network/basenetworks.py#L174).

After this operation, the input stem definition basically goes from:

```python
Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False),
BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True),
ReLU(inplace),
MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False), 
... resnet blocks follow ...
```

to

```python
(0): Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace)
)
... resnet blocks follow ...
```

At training time, the backbone's weights are frozen for one epoch, before being unfrozen and retrained for 75 epochs (by default).

*Have you observed any gains in using a pretrained ResNetv2 as opposed to using a "virgin" backbone? After the max pooling layer at the end of the input stem has been removed, haven't the downstream weights/biases become completely meaningless anyway?*

I must be missing something basic and would greatly appreciate if you could take the time to clarify this for me.

Thanks again for this awesome work, @svenkreiss !

**Comment by svenkreiss** [comment]
Great to see enthusiasm for OpenPifPaf. Thank you. Please share widely :) 

I agree that the meaning of the convolutional weights changed with the modification, but they didn't become useless. Leaving out the input pooling layer just means that the following layers resolve to smaller image patches. In the interpretation where convolutions are regarded as pattern matchers, the ResNet blocks still match lines and corners etc and the higher blocks still match more complicated patterns, just at a smaller scale in the input image. But then ImageNet is trained on 224x224 images whereas we can train at a different input image size to compensate any mismatch in pattern scales and in fact the default training size for OpenPifPaf is 401x401.

I have tried to train starting from randomly initialized weights and it gave worse results which are shown in [docs/studies.ipynb](https://github.com/vita-epfl/openpifpaf/blob/master/docs/studies.ipynb) in the section "Without ImageNet Pretraining".

I hope this helps.

**Comment by philferriere** [comment]
I get the intuition but am still surprised that the network would be robust enough and make up for the mismatch in resolution so easily. I learned something new today ;)

Thanks for the prompt answer and detailed explanation, @svenkreiss!
