### ISSUE TITLE
Evaluation with multi-scale input is not good

### ISSUE THREAD

**Issue by USTClj** [vita-epfl/openpifpaf#58]
Hi, @svenkreiss, your model is pretty good with only single input. I ran the ResNet101 model with three scale input (*0.5, *1, *2), the AP performance is much worse at 0.32 AP. Did I miss sth? I just run the command:

> python -m openpifpaf.eval_coco --checkpoint outputs/resnet101block5-pif-paf-edge401-190412-151013.pkl --long-edge=641 --loader-workers=8 --three-scale

And the multi-scale option (not 3 scale option) is very slow while the single input is pretty fast.

**Comment by USTClj** [comment]
Update. Only the  result with multi-scale input on test-dev subset is poor, while on validation subset the performance is still good enough. I don not know why yet.

**Comment by svenkreiss** [comment]
I am not happy with the current three-scale performance, but I have not seen such a large drop as you. Please write back about what you find.

**Comment by USTClj** [comment]
Thank you for your reply. Perhaps, most people wish to perform well on single input in practice :)
I just ran with command line and didn't have any changes to the code.

**Comment by svenkreiss** [comment]
Yes, anything other than single-scale are undocumented features for now.
Something is not right there. Haven't had the time yet to figure out why three-scale doesn't improve the results more.

**Comment by USTClj** [comment]
Thank you for your sharing. Best wishes.
