### ISSUE TITLE
load model directly?

### ISSUE THREAD

**Issue by junedgar** [vita-epfl/openpifpaf#59]
I tried to load the pre_trianed model directly.
```
import torch
torch.load("checkpoint_path")
```
but get the error:
```
Traceback (most recent call last):
  File "/Users/edgar/project/python37/rtsp_warp/src/pose/inference.py", line 101, in <module>
    a = torch.load('/Users/edgar/Desktop/resnet50block5.pkl')
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'openpifpaf'
```
Can you give me some advices?

**Comment by junedgar** [comment]
@svenkreiss Can you give me some advices to process this problem?

**Comment by svenkreiss** [comment]
Is `openpifpaf` importable?

**Comment by junedgar** [comment]
@svenkreiss 
Thank you for your reply!
If I installed the openpifpaf use pip,  torch can load the model directly.
And I found that you save the model directly, not save the model.state_dict() as usual, which maybe lead to the model definition was saved at some time.
But i still have a little confusion about how can i import the openpifpaf directly,  not through install the openpifpaf package,  when I load the model？

**Comment by svenkreiss** [comment]
Not everything that is done usually is good. I am not saving the state_dict
on purpose.

It is not possible to load the model without openpifpaf being installed.
Saving only the state_dict wouldn't change that. Then you could load the
state_dict but not do anything with it until you load it into an openpifpaf
model for which it would need to be installed.

Do you have a specific use case you can share with us?

**Comment by junedgar** [comment]
Thank you for your reply!
I just tried to extract a light inference framework from your work, not do something special use.
I learned many skills from your project!
Thank you very much!
