### ISSUE TITLE
Real-Time Applications

### ISSUE THREAD

**Issue by aaramirezd** [vita-epfl/openpifpaf#7]
Is it possible to execute the model inference in run-time(==real time)?
Thks

**Comment by svenkreiss** [comment]
It depends on the image size. I just made a little web demo that runs at 5FPS on a laptop without GPU acceleration: https://github.com/vita-epfl/openpifpafwebdemo
We also have timing numbers in Table 4 in our paper: https://arxiv.org/abs/1903.06593

**Comment by FoolishMao** [comment]
The decode process cost the most time, so i change the 8 scale to 4, and it's faster(192x108 get 30FPS on 1080Ti).I think it's a method to run realtime? @svenkreiss

**Comment by svenkreiss** [comment]
You run the Webbrowser Demo with 30FPS? Wow, I have not seen that. Do you mind posting a screenshot?

**Comment by FoolishMao** [comment]
I run webcam.py in this project. The  time decode process cost depends on the number of keypoints. Here is my log：
![image](https://user-images.githubusercontent.com/36061157/54586823-254f2780-4a59-11e9-9d79-927c6d6ead57.png)
but the FPS decrease with the number of keypoints increase.
![image](https://user-images.githubusercontent.com/36061157/54587014-ca6a0000-4a59-11e9-976e-f49ef1c5e2fd.png)
https://github.com/vita-epfl/openpifpaf/blob/b9857dcbae948de1a0bb01feed6cfd8b0ca3189d/openpifpaf/decoder/factory.py#L61
I change model.io_scales()[-1] to  model.io_scales()[-1]/2, and draw more simply

**Comment by svenkreiss** [comment]
Nice! Thanks for sharing.

In `webcam.py`, drawing happens in the same thread and is a real bottleneck. This is not an issue for the web browser demo.

**Comment by yw155** [comment]
Hi @svenkreiss, is it possible to accelerate the decode process if implementing the decode part in C++ ?

**Comment by yanqian123** [comment]
@FoolishMao hello，i want to ask a question "how to use GPU" ?? just about "--disabled cuda ==False" or there other codes that need changed?

**Comment by yanqian123** [comment]
I am looking for your reply , thanks a lot

**Comment by FoolishMao** [comment]
> I am looking for your reply , thanks a lot

you need do nothing if you want to use gpu,  if you want use cpu, just "--disable cuda"
