### ISSUE TITLE
Do you think EfficientNet would improve results/inference?

### ISSUE THREAD

**Issue by esgnn** [vita-epfl/openpifpaf#70]
I am not sure whether it is relevant or not, what do you think? If yes, are you planning to train a model based on it?
Great estimator btw. Also thanks for the effortless pip installation.

**Comment by svenkreiss** [comment]
You are welcome :)

I only had a brief look at the paper. Do the scaling rules generalize beyond classification? Or is it generally a better architecture even if it would be necessary to re-derive the scaling rules for keypoint tasks?

**Comment by esgnn** [comment]
Unfortunately, I have no idea :/
