### ISSUE TITLE
Predict module saves bboxes into json WITHOUT filtering zero values

### ISSUE THREAD

**Issue by innjoshka** [vita-epfl/openpifpaf#79]
**Predict module** saves bboxes into json not in correct way. Bboxes computed from keypoints are computed with **zeros**, so almost all saved results into json has zero numbers!. However, **show module** filters zero points and works fine. I have changed function to work correctly and consider filtering zero kps.

**With filtering zero keypoints**
```
[            if 'json' in args.output_types:
                with open(output_path + '.pifpaf.json', 'w') as f:
                    json.dump([
                        {'keypoints': np.around(kps, 1).reshape(-1).tolist(),
                         'bbox': [np.min(kps[:, 0][kps[:, 2] > 0]), np.min(kps[:, 1][kps[:, 2] > 0]),
                                  np.max(kps[:, 0][kps[:, 2] > 0]), np.max(kps[:, 1][kps[:, 2] > 0])]}
                        for kps in keypoint_sets
], f)
```

**Without filtering zero keypoints**
```
            if 'json' in args.output_types:
                with open(output_path + '.pifpaf.json', 'w') as f:
                    json.dump([
                        {'keypoints': np.around(kps, 1).reshape(-1).tolist(),
                         'bbox': [np.min(kps[:, 0]), np.min(kps[:, 1]),
                                  np.max(kps[:, 0]), np.max(kps[:, 1])]}
                        for kps in keypoint_sets
], f)
```

**Comment by svenkreiss** [comment]
Thanks for reporting this!

I have opened a Pull Request with a fix. Note that the fix produces a different result because I am following now the COCO convention like the rest of the code where a bounding box is given by `[x, y, w, h]` instead of the corners of the box. Please let me know if you have any comments.
