### ISSUE TITLE
What version of python and pytorch is used?

### ISSUE THREAD

**Issue by yw155** [vita-epfl/openpifpaf#8]
Hi @svenkreiss, thanks for your great work. Could you share the information of your software environments? Thanks.

**Comment by svenkreiss** [comment]
It's only for Python3. Python2 is not supported.

All other dependencies should be pulled in automatically when your run `pip install`. They are defined in `setup.py`:

```py
    install_requires=[
        'matplotlib',
        'pysparkling',  # for log analysis
        'python-json-logger',
        'scipy',
        'torch>=1.0.0',
        'torchvision',
    ],
```

The readme should mention the Python3 requirement somewhere. I'll leave this issue open for that.
