### ISSUE TITLE
some questions about source code

### ISSUE THREAD

**Issue by murdockhou** [vita-epfl/openpifpaf#88]
Hi, thanks for your work. I'm reading your source code about ' the process of decoding pifpaf' and find somewhere that confused me.

1.  in `openpifpaf/decoder/pifpaf.py, function PifPafGenerator._target_intensities`,  what's meaning about function `cumulative_average`. By the way, what i understand about function `scalar_square_add_gauss` is some way like to refine the `x y number of pif field`, is it right or not?

2. what's meaning about code `scores_b = scores * (pifhr_floor + (1.0 - pifhr_floor) * pifhr_b)` in `openpifpaf/decoder/pifpaf.py, function PifPafGenerator._score_paf_target`?  And i'm not sure about what meaning of  var `pifhr_b` .

Could you please give me some advice about these question and, maybe it's best to give me more detailed information about how to decode the `pif field and paf field` that network output, and how to finally to get the final `skeleton` using `pif and paf info`. I'm a little confused about the process and really really need your help. Sorry for troubling  you and wish your reply.

best wishes,
matt

**Comment by svenkreiss** [comment]
Hi @murdockhou ,

Somehow this issue escaped my attention.
In the meantime, did some questions clear up? 
Anything specific I can still help with?

Sven

**Comment by IQ17** [comment]
what's the usage of cumulative_average function? I have not found wherever it is needed.

**Comment by IQ17** [comment]
why we need to call function cumulative_average? I have not found any where it is needed.
