### ISSUE TITLE
whether support multi-scale training?

### ISSUE THREAD

**Issue by jiachen0212** [vita-epfl/openpifpaf#92]
hello @svenkreiss , i found the code can only support 401 and 641 training size? 
can i use multi-scale during training? maybe do something in datasets.py?

**Comment by svenkreiss** [comment]
Multi-scale training is supported in the sense that input images are resized to random scales. Therefore, the same input image is trained for different scales in different epochs. 

The 401px is the training image size to make a batch. You cannot put different sizes in the same batch and OpenPifPaf does not support different scales across batches.

**Comment by jiachen0212** [comment]
@svenkreiss  i found, scale = 40*x + 1 supported...  so I set a larger scale value for my own training and it looks work better.

**Comment by svenkreiss** [comment]
Sounds great!

Generally arbitrary sizes are supported but the ResNet backbone tiles them perfectly with sizes of the form 16*x+1.

I used to be restricted by the GPU memory. Sounds like a good idea to increase the size now. Maybe you could share some numbers once you have them: which backbone, which training size, which COCO AP you get.
