### ISSUE TITLE
Training on a subset of the skeleton

### ISSUE THREAD

**Issue by stbjelcevic** [vita-epfl/openpifpaf#93]
Is it possible to modify the model so that it only outputs keypoints for certain body parts (lets say wrists, elbows, shoulders, and eyes)?

If so, what are the steps needed to do this? 

I imagine I will need to modify the dataset, but that will be straight forward. I am more asking about what needs to be done with the model architecture.

**Comment by svenkreiss** [comment]
Shouldn't be too hard. Search for COCO_PERSON_SKELETON in the code. That will have to be replaced by a custom skeleton. And the number of fields needs to be adjusted but that is also a variable for the main constructors. There are already a denser skeleton and a kinematic tree skeleton which modify the number of PAF fields, etc.

I am quite interested to generalize the code to arbitrary skeletons. Don't have a great interface for that at the moment, but at the core the code is flexible.

**Comment by stbjelcevic** [comment]
I had the same thought as you initially. Have you done something like this before, or are you just suggesting? 

The denser/kinematic trees still use 17 PIFs, so I agree that modifying the skeleton by using all the keypoints should be straight forward. I'm trying to just use 9 PIFs (nose, eyes, shoulders, elbows, wrists) and 10 PAFs connecting them. 

One approach I considered was just zeroing out all of the keypoints I don't care about, but I don't want to increase the dimensionality of the problem for no reason.

**Comment by stbjelcevic** [comment]
Ok I was actually able to figure it out after playing around a little bit more and following your advice. I ended up defining my own skeleton and sigmas list in data.py and modifying imports to import the new skeleton/sigma list. Also had to add a few conditionals to check for 'paf10' and 'pif9' to actually set the correct variables to the modified skeleton. Thanks for the advice!

**Comment by svenkreiss** [comment]
Great to hear. Hopefully we will have a more streamlined interface for this
at some point.
