### ISSUE TITLE
decording by CUDA

### ISSUE THREAD

**Issue by lianuo** [vita-epfl/openpifpaf#94]
Thank you for your excellent works !
I have test the running time
0.042s ->network forward
0.057s ->decording
0.046s ->draw and display
I found the decording is done all by CPU, do you have plan to implment it in GPU by CUDA? I think that will  dramatically improve the speed.

Thank you

**Comment by svenkreiss** [comment]
Thanks for your message and interest. Can you post more details on how to implement the decoder in CUDA?

**Comment by lianuo** [comment]
@svenkreiss 
in the paper, equation 1 and 2 can be done on GPU by implement CUDA kernel with  pytorch's CUDAExtension, BuildExtension,and the keypoints peaks  and connet keypoints could also run with CUDA,and return the pose infomation to CPU.

**Comment by svenkreiss** [comment]
Sounds like you have a plan. I am not at all familiar with PyTorch's CUDAExtension, so your help is much appreciated. So far, my approach has been to identify the parts that seem unreasonably slow and only moving those to C (not CUDA).

For decoder performance, please also see the [docs/performance.md](https://github.com/vita-epfl/openpifpaf/blob/master/docs/performance.md) with some studies what is particularly slow in the decoder and note that some parts are already in C.

There is also a short set of notes now in [CONTRIBUTING](https://github.com/vita-epfl/openpifpaf/blob/master/CONTRIBUTING.md).

Looking forward to your ideas and contribution.

**Comment by lianuo** [comment]
@svenkreiss Sorry for the delay , busy on something else for months, I plan to start recently. Have anyone else did this these days?

**Comment by kepler62f** [comment]
Is the docs/performance.md document still available? don't seem to find it... 

> Sounds like you have a plan. I am not at all familiar with PyTorch's CUDAExtension, so your help is much appreciated. So far, my approach has been to identify the parts that seem unreasonably slow and only moving those to C (not CUDA).
> 
> For decoder performance, please also see the [docs/performance.md](https://github.com/vita-epfl/openpifpaf/blob/master/docs/performance.md) with some studies what is particularly slow in the decoder and note that some parts are already in C.
> 
> There is also a short set of notes now in [CONTRIBUTING](https://github.com/vita-epfl/openpifpaf/blob/master/CONTRIBUTING.md).
> 
> Looking forward to your ideas and contribution.

**Comment by twmht** [comment]
@lianuo 

Have you done with cuda?
