### ISSUE TITLE
Any plan to adding support for lightweight backbone network?

### ISSUE THREAD

**Issue by alphinside** [vita-epfl/openpifpaf#95]
Hi guys, a very impressive work ( the gridless approach is very cool ). Anyway any chance you guys implement the shufflenet v2 / mobilenet v3 as the backbone nets? Currently I'm still trying to grasp the modified resnet you provide though. Thanks guys

**Comment by svenkreiss** [comment]
I hope to have ShuffleNet v2 in the next version.

**Comment by svenkreiss** [comment]
With the new version 0.8.0 you can use:
* `--checkpoint shufflenetv2x1`
* `--checkpoint shufflenetv2x2`
