### ISSUE TITLE
Can you share the command which you used to train the provided resnet152 model?

### ISSUE THREAD

**Issue by CHUNYUWANG** [vita-epfl/openpifpaf#98]
Is it the same as:
python3 -m openpifpaf.train \
  --lr=1e-3 \
  --momentum=0.95 \
  --epochs=75 \
  --lr-decay 60 70 \
  --batch-size=8 \
  --basenet=resnet152block5 \
  --head-quad=1 \
  --headnets pif paf \
  --square-edge=401 \
  --regression-loss=laplace \
  --lambdas 30 2 2 50 3 3 \
  --freeze-base=1

**Comment by CHUNYUWANG** [comment]
Besides, is the freeze-base option critical in getting a good model?

**Comment by svenkreiss** [comment]
The first line in the log file contains all the arguments used to run the train command.

**Comment by CHUNYUWANG** [comment]
Thanks!
