### ISSUE TITLE
Different setting in train and val process

### ISSUE THREAD

**Issue by USTClj** [vita-epfl/openpifpaf#99]
Hi, I'd found that:

https://github.com/vita-epfl/openpifpaf/blob/020cf5852a9f43a6cb84b7a4774101f3c0305a54/openpifpaf/network/nets.py#L138

However, during training, the BN's parameter momentum=0.9. Why you set a different value?

**Comment by svenkreiss** [comment]
SGD momentum and BN momentum are independent things.

On the command line you set SGD momentum and in the function you point out the BN momentum is set.

**Comment by USTClj** [comment]
Thank you, my misunderstanding. But the eps in Bn is also reset, does it harm the performance? As we known, BN layers is sensitive to values and it needs flop 32 precision to keep stabilization.
